### ISSUE TITLE
Add a contributing.md

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/how-to-contribute-to-open-source#1]

**Comment by jihdeh** [comment]
@QuincyLarson Please can i take on this?

**Comment by QuincyLarson** [comment]
@jihdeh Definitely. Let me know if you need any help. 😄

**Comment by erictleung** [comment]
Looks like this issue can be closed because #10 resolves this.

**Comment by raisedadead** [comment]
Closing. :wink:
