### ISSUE TITLE
Add every day git commits to git section

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#119]
giteveryday - A useful minimum set of commands for Everyday Git

https://git-scm.com/docs/giteveryday

To whoever picks up this issue, please include `Closes #119` in your pull request message so that it references back to this issue.

**Comment by sblasa** [comment]
@erictleung Hi, I’d like to help on this.

**Comment by erictleung** [comment]
@sblasa thanks for the interest! It looks like you've contributed before and I'd like to keep this issue open for new contributors. I hope you understand.

**Comment by isaacwagithub** [comment]
Hey erictleung. I'm a first timer and I would trike to help

**Comment by isaacwagithub** [comment]
Oooops! Like to help not trike

**Comment by erictleung** [comment]
@isaacwagithub go for it! In your pull request message, add in `Closes #119` so that it can be traced back to this issue. Thanks!

**Comment by ProcrastinatorCp** [comment]
@isaacwagithub  Hi, are you still working on it ? If not, I would like to contribute. 
If it's already solved, please close this. 
Please let me know. Thanks

**Comment by erictleung** [comment]
@ProcrastinatorCp thanks for checking in! I would go ahead and take it up if the individual doesn't respond by the end of the weekend. Thanks for your interest!

**Comment by ProcrastinatorCp** [comment]
@erictleung , Could you please review https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/140
