### ISSUE TITLE
Add Docker

### ISSUE THREAD

**Issue by shubheksha** [freeCodeCamp/how-to-contribute-to-open-source#12]
[Contributor guide](https://docs.docker.com/opensource/workflow/make-a-contribution/)
Issue label: [exp/beginner](https://github.com/docker/docker/issues?q=is%3Aopen+is%3Aissue+label%3Aexp%2Fbeginner)

**Comment by meetsha** [comment]
Can you help? Do I create a new section? Or should I add this to "Contributing to open source in general" section?

**Comment by shovanch** [comment]
Hello, Is anyone working on this? If not, can I take this?

**Comment by karthicktv** [comment]
@shovanch are you still going to work on this? what's your plan?

**Comment by schandan696** [comment]
Hey can i add PR for Docker or anyone working.?
