### ISSUE TITLE
Add table of contents

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#121]
Add this just above the first section "Contributing to open source in general"

```
**Table of Contents**

- [Contributing to open source in general](#contributing-to-open-source-in-general)
- [Direct GitHub searchs](#direct-github-searchs)
- [Mozilla's contributor ecosystem](mozillas-contributor-ecosystem)
- [Useful articles for new open source contributors](#useful-articles-for-new-open-source-contributors)
- [Using version control](#using-version-control)
- [Open Source books](#open-source-books)
- [License](#license)
```

It should produce something like this

**Table of Contents**

- [Contributing to open source in general](#contributing-to-open-source-in-general)
- [Direct GitHub searchs](#direct-github-searchs)
- [Mozilla's contributor ecosystem](mozillas-contributor-ecosystem)
- [Useful articles for new open source contributors](#useful-articles-for-new-open-source-contributors)
- [Using version control](#using-version-control)
- [Open Source books](#open-source-books)
- [License](#license)

**Comment by jj-owens** [comment]
Since this looks like it's still open, I'll work on it!

**Comment by erictleung** [comment]
Closed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/122
