### ISSUE TITLE
Add Flight rules for git in Version Control Section

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#125]
Link: https://github.com/k88hudson/git-flight-rules

To whoever picks this up, please add `Closes #125` to your pull request message so that it links back to this issue.

**Comment by guipaes** [comment]
@erictleung Hi, I'd like to help with this issue.

**Comment by erictleung** [comment]
@guipaes go for it! It should be added to the git and version control section. Let us know in the [contributors](https://gitter.im/FreeCodeCamp/Contributors) Gitter room if you have any questions.
