### ISSUE TITLE
Add Open Source Guides for the Enterprise

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#126]
Add to contributing to open source in general

https://www.linuxfoundation.org/resources/open-source-guides/

To whoever takes this up, add `Closes #126` to your pull request message so that it'll reference back to this issue.

**Comment by mrduguid** [comment]
Hello erictleung. I would like to have a go at this one.

**Comment by erictleung** [comment]
@mrduguid go for it! Let me know if you have any questions about contributing. Feel free to visit the [contributors](https://gitter.im/FreeCodeCamp/Contributors) chat room for help if needed.
