### ISSUE TITLE
Add Gnome

### ISSUE THREAD

**Issue by shubheksha** [freeCodeCamp/how-to-contribute-to-open-source#13]
[New Contributor Guide](https://wiki.gnome.org/Newcomers)

**Comment by TushaarGVS** [comment]
Hey, what has to be done here? Can you please help me out?

**Comment by meetsha** [comment]
I just created a pull request to fix this issue. My first pull request(!!!). Can you please review it:)

**Comment by shubheksha** [comment]
@tushaarGVS - since @meetsha already submitted a PR for this issue, would you mind working on something else? I'd be happy to help you out with any other issue you pick on which someone hasn't commented already.

@meetsha - from next time onwards, please pick up an issue on which someone hasn't already expressed interest in working through a comment and a maintainer of the project is yet to follow up?
This will help you avoid duplication in effort later on. If two people start working on the same issue and I sincerely hope @TushaarGVS didn't start working on this one, it'll lead to wastage of one person's effort and time. We don't want that to happen. :smile:

**Comment by meetsha** [comment]
I am really sorry @TushaarGVS. I will keep that in mind @shubheksha.
