### ISSUE TITLE
Keyboard software that types by reading the character

### ISSUE THREAD

**Issue by Nikz56** [freeCodeCamp/how-to-contribute-to-open-source#130]
I have thought to make a key board software that types on itself after reading character inputs as image or text.if we can give image as input and the software recognizes the text and type it automatically.

**Comment by erictleung** [comment]
@Nikz56 thanks for letting us know! However, please leave these issues for contributing useful links to projects to contribute to or include resources to help others contributing to open source. Happy coding!
