### ISSUE TITLE
Add Casualdate

### ISSUE THREAD

**Issue by StellarDoor5319** [freeCodeCamp/how-to-contribute-to-open-source#132]
Label: https://github.com/StellarDoor5319/casualdate/labels/good%20first%20contribution
Contribution guide: https://github.com/redfin/react-server/blob/master/CONTRIBUTING.md
Docs: http://www.rubydoc.info/github/StellarDoor5319/casualdate

**Comment by StellarDoor5319** [comment]
I'm still writing the CONTRIBUTING file - it might not get pushed for half an hour or so

**Comment by pawgrmr** [comment]
Hi Eric, could I get some clarification on what needs to be done? It's my first open-source contribution attempt so some guidance would be much appreciated :)

**Comment by pawgrmr** [comment]
Hi @erictleung I've just submitted a PR for this issue. Could you please review and let me know if I'm on the right track? Thanks!

**Comment by erictleung** [comment]
Closed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/151
