### ISSUE TITLE
Add "An Open Source Etiquette Guidebook"

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#135]
Add to contributing to open source in general. 

https://css-tricks.com/open-source-etiquette-guidebook/

**Comment by kkavita92** [comment]
Happy to do this - do you want it as a README in the project folder?

**Comment by erictleung** [comment]
@kkavita92 thanks for your interest! Yes, I was thinking of putting it in the main README file under ["Contributing to open source in general"](https://github.com/freeCodeCamp/how-to-contribute-to-open-source#contributing-to-open-source-in-general). Let me know if you have other questions. Thanks!

**Comment by karuna24s** [comment]
Hi @erictleung and @kkavita92! @kkavita92 are you still working on this issue if not can I work on it?

**Comment by erictleung** [comment]
@karuna24s I'd say you're free to work on this! Enough time has passed that I think it would be okay to pick up now. Good luck!

**Comment by karuna24s** [comment]
Thanks @erictleung I will work on it.
