### ISSUE TITLE
Add PublicLab

### ISSUE THREAD

**Issue by seafr** [freeCodeCamp/how-to-contribute-to-open-source#141]
Public Lab (org)
- [Plots2](https://github.com/publiclab/plots2) (project)
  - [Contributing guide](https://github.com/publiclab/plots2/blob/master/CONTRIBUTING.md)
  - Issue labels:
    - [first-timers-only](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3Afirst-timers-only)
    - [help-wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3Ahelp-wanted)
    - [fto-candidate](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3Afto-candidate)

**Comment by cameocodes** [comment]
Happy to take this one on if it's still available.

**Comment by erictleung** [comment]
@cameocodes go for it! This should go into the [PROJECTS.md](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/PROJECTS.md) file. Let me know if you have any questions. Thanks!

**Comment by arshadkazmi42** [comment]
is it still open? Would like to take this up

**Comment by erictleung** [comment]
@arshadkazmi42 looks like it is, feel free to contribute this to the projects file. Within the pull request, please put `Closes #141` in the message body so that it references this issue. Thanks!

**Comment by arshadkazmi42** [comment]
Awesome. Will take this up. And I will add the reference to the issue too 👍
