### ISSUE TITLE
Add "Software Release Practice HOWTO"

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#145]
Link: http://en.tldp.org/HOWTO/Software-Release-Practice-HOWTO/

Add to the Open Source books section.

**Comment by Neidley** [comment]
May I claim this issue?

**Comment by erictleung** [comment]
@Neidley go for it! Let me know if you have any issues submitting a pull request.

**Comment by Neidley** [comment]
PR #146

**Comment by Neidley** [comment]
Should be good now :) Thanks for letting me work on this issue!

**Comment by erictleung** [comment]
@Neidley nice job with the PR and taking time to put back the original styling of the file. Not sure why this issue didn't auto close because of those issue closing keywords. I guess those only work in the original first commit? Anyways, thanks for contributing! Closing this issue as fixed.
