### ISSUE TITLE
Add Test Kitchen

### ISSUE THREAD

**Issue by shubheksha** [freeCodeCamp/how-to-contribute-to-open-source#15]
http://kitchen.ci/
Issue label: [*](https://github.com/test-kitchen/test-kitchen/issues?q=is%3Aopen+is%3Aissue+label%3A%E2%AD%90%EF%B8%8F)

**Comment by shubheksha** [comment]
@0110G - Feel free to pick it up!

**Comment by erictleung** [comment]
To those who haven't contributed before to this repository or are wanting to get more comfortable contributing, please take a look at #283 for an example of what is needed for this issue.

**Comment by Pandorandom** [comment]
Hi @erictleung, I have taken a stab at this issue, and created pull request #320 . If I have broken some etiquette, please let me know and I am happy to make any corrections.

**Comment by erictleung** [comment]
@Pandorandom all is well my friend! I've taken a look at and approved it. I edited it a little bit because the link you used was a little different that the suggested link above, which was difficult to read.

Closed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/320
