### ISSUE TITLE
Add Think Like (a) Git to version control section

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#153]
Link: http://think-like-a-git.net/

Add: 

```
## Using version control
...
- [Think Like (a) Git](http://think-like-a-git.net/) - Git introduction for "advanced beginners," but are still struggling, in order to give you a simple strategy for safely experiment with git.
```

**Comment by ravk1234** [comment]
Can I try this?

**Comment by ravk1234** [comment]
In which file do I have to do this?

**Comment by shubheksha** [comment]
@ravk1234, sure, go ahead!
This is the file that needs to be changed: https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/README.md#using-version-control

**Comment by ravk1234** [comment]
how to submit pull request for this issue?

**Comment by ravk1234** [comment]
I tried pull rquest but travis ci failed

**Comment by ravk1234** [comment]
In    ## Useful articles for new open source contributors
   www.nearform.com/nodecrunch/first-time-with-open-source
This link is not working . That is why Travis CI build failed. Should I remove this link?
