### ISSUE TITLE
Add Dita Ota

### ISSUE THREAD

**Issue by shubheksha** [freeCodeCamp/how-to-contribute-to-open-source#16]
http://www.dita-ot.org/
Issue label: [good first bug](https://github.com/dita-ot/dita-ot/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+bug%22)

**Comment by prashantpcm94** [comment]
i want to work on this

**Comment by shovanch** [comment]
Hi, is anyone working on this?

**Comment by erictleung** [comment]
To those who haven't contributed before to this repository or are wanting to get more comfortable contributing, please take a look at #281 for an example of what is needed for this issue.

**Comment by rharill** [comment]
I will work on this
