### ISSUE TITLE
Add Hoodiehq

### ISSUE THREAD

**Issue by shubheksha** [freeCodeCamp/how-to-contribute-to-open-source#17]
https://github.com/hoodiehq/camp
https://github.com/hoodiehq/hoodie

**Comment by aabi01** [comment]
i am up for it !

**Comment by bismarkhenao** [comment]
[Camp project](https://github.com/hoodiehq/camp) does not have any CONTRIBUTING.md file

**Comment by erictleung** [comment]
To those who haven't contributed before to this repository or are wanting to get more comfortable contributing, please take a look at #282 for an example of what is needed for this issue.

**Comment by Opinion** [comment]
I'll give it a shot @erictleung

**Comment by erictleung** [comment]
Closed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/385
