### ISSUE TITLE
CI builds failing

### ISSUE THREAD

**Issue by sdabhi23** [freeCodeCamp/how-to-contribute-to-open-source#177]
Currently all Travis builds are failing due to a broken link.

[FreeCodeCamp/FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) have deleted  their `staging` branch and the link to `CONTRIBUTING.md` refers to the file on the staging branch.

### Solution
Change the link to refer to `CONTRIBUTING.md` on the master branch.

**Comment by erictleung** [comment]
This should be the correct link for whoever wants to pick this up:

https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md

**Comment by anabellaspinelli** [comment]
Hey! Can I take this? :)

**Comment by shubheksha** [comment]
Sure, go ahead!

**Comment by erictleung** [comment]
Closing issue as fixed by #179.
