### ISSUE TITLE
Add Jenkins

### ISSUE THREAD

**Issue by shubheksha** [freeCodeCamp/how-to-contribute-to-open-source#19]
https://wiki.jenkins-ci.org/display/JENKINS/Beginners+Guide+to+Contributing

**Comment by meetsha** [comment]
Can I work on this issue?

**Comment by susg** [comment]
Do I need to make a new section like " Mozilla contributor ecosystem " or just add it in the " Contributing to open source in general " section ?

**Comment by erictleung** [comment]
To those who haven't contributed before to this repository or are wanting to get more comfortable contributing, please take a look at #284 for an example of what is needed for this issue.

**Comment by geek-2002** [comment]
can i work on this issue

**Comment by erictleung** [comment]
@geek-2002 you already have a pull request open https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/390. I would say to complete that and leave this issue for another person to work on. I hope you understand. Let me know if you have any questions on that other pull request.

**Comment by Satzyakiz** [comment]
Can I work on this issue ? I am new to Open Source and want to start contributing.

**Comment by aveshfar** [comment]
can i work on this issue????

**Comment by erictleung** [comment]
@aveshfar if you're still interested, it is all yours! Let us know if you have any questions 👍

**Comment by catboxer** [comment]
First time working on an issue. Can I help? Thank you!

**Comment by erictleung** [comment]
@catboxer this still looks open! Take a look at https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/284 for an example of how this should look like :+1:

**Comment by chincholikarsalil** [comment]
@erictleung
Hey! Is it okay if I work on this?

**Comment by Kajal03** [comment]
@erictleung Hey, I have raised a PR for this issue. Can you please verify?
