### ISSUE TITLE
Add a license.md file - probably MIT, but open for discussion

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/how-to-contribute-to-open-source#2]

**Comment by erictleung** [comment]
Considering this repo, from what I understand, won't be code/software, the MIT license might not be the most appropriate license. Using the [Choose a License](http://choosealicense.com) website, they have [options for non-software](http://choosealicense.com/non-software/), namely Creative Commons licenses that may be more appropriate. Just my two cents.

**Comment by QuincyLarson** [comment]
@erictleung you're right. Since this won't be software, CC-4.0-BY-SA is probably the right license. This is what the most popular non-code repo (https://github.com/vhf/free-programming-books) uses.

**Comment by ShadowTwo** [comment]
Good day all,

I am a first timer and I was looking for a simple project to get started on, and this looks like a great starting place, and links made for some good info.

I read over the different options I think you are spot on with CC-4.0-BY-SA. Do you mind if I create the file and create a pull request for this?

**Comment by QuincyLarson** [comment]
@ShadowTwo please :)

I will accept your PR.
