### ISSUE TITLE
Add nteract

### ISSUE THREAD

**Issue by captainsafia** [freeCodeCamp/how-to-contribute-to-open-source#24]
Please come contribute to nteract!

You can use the new-contributor-friendly label to find issues that are easy for new contributors to tackle.

We also have issues with a mentoring-available tag in which a maintainer will be able to provide 1-on-1 assistance with the issue.

[nteract](https://github.com/nteract/nteract)
[new-contributor-friendly](https://github.com/search?utf8=%E2%9C%93&q=user%3Anteract+is%3Aissue+is%3Aopen+is%3Anew-contributor-friendly)
[mentoring-available](https://github.com/search?utf8=%E2%9C%93&q=user%3Anteract+is%3Aissue+is%3Aopen+is%3Amentoring-available&type=Issues&ref=searchresults)

**Comment by shovanch** [comment]
Is anyone working on this? I would like to take this.

**Comment by rgbkrk** [comment]
I don't think anyone is. Based on digging through the linked up-for-grabs site, I think you can add nteract in the style they mention here: https://github.com/up-for-grabs/up-for-grabs.net#add-a-project

**Comment by shovanch** [comment]
Thanks for the response. I would start working on it then.

**Comment by erictleung** [comment]
Closed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/80. Happy coding, all!
