### ISSUE TITLE
Add Servo

### ISSUE THREAD

**Issue by shubheksha** [freeCodeCamp/how-to-contribute-to-open-source#25]
https://starters.servo.org/
https://github.com/servo/servo/blob/master/CONTRIBUTING.md
Issue label: [E-easy](https://github.com/servo/servo/issues?q=is%3Aissue+is%3Aopen+label%3AE-easy)

**Comment by aabi01** [comment]
@shubheksha  Can i take this issue?

**Comment by vikramnr** [comment]
@erictleung @shubheksha Can I raise PR for this one? If so in which `section` it has to be added?

**Comment by erictleung** [comment]
@vikramnr this should be added to the `PROJECTS.md` file https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/PROJECTS.md. Let us know if you have any questions about contributing or have issues trying to make changes if you're still interested in contributing! :+1:

**Comment by kumarrajan4264** [comment]
Is the issue still open?
which links I have to add?

**Comment by erictleung** [comment]
@kumarrajan4264 whoops. Looks like I forgot to close this when I merged in #71, which fixes this issue. Take a look at the other issues in the repository for other issues you can work on. Happy coding!
