### ISSUE TITLE
Translate to Chinese

### ISSUE THREAD

**Issue by zhirui1994** [freeCodeCamp/how-to-contribute-to-open-source#266]
Thanks for open source to this. But for chinese, like me, somewhere it is hard for us to understand. So, I want a chinese translate base to this source.
And, I'll also do my best to translate this source to chinese.
Can some one help me?

**Comment by erictleung** [comment]
@zhirui1994 thanks for your enthusiasm to contribute!

We welcome translations of other languages. Please name the new file `README-CN.md`. Can you be more specific on what kind of help you need? Have you made a pull request before? Or do you just need more specifics on contributing to this repository? Thanks!

**Comment by cc189** [comment]
Sounds like a good idea, I'd love to join this idea

**Comment by zhirui1994** [comment]
@erictleung Thanks for your reply. sure, I have a Pull Request about this, #269 .  I get get stuck in it . The Travis CI build failed,  but I don't know where‘is in it. Can you help me about it? Thanks!

**Comment by erictleung** [comment]
Closed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/269
