### ISSUE TITLE
Add react-server

### ISSUE THREAD

**Issue by doug-wade** [freeCodeCamp/how-to-contribute-to-open-source#27]
The tag: https://github.com/redfin/react-server/labels/good%20first%20contribution
The contributing guide: https://github.com/redfin/react-server/blob/master/CONTRIBUTING.md
The docs: https://react-server.io

**Comment by shreyateeza** [comment]
Hi @doug-wade ! Can you please explain me what to do here? I would like to work on this.

**Comment by systimotic** [comment]
Hi @shreyateeza! I think the idea is to add these links to the [PROJECTS.md](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/PROJECTS.md)

**Comment by erictleung** [comment]
@shreyateeza yes, as @systimotic mentioned, we've moved these project links to the PROJECTS.md file. Take a look at the linked file above for examples of how to format these. I've been meaning to go through these issues and make them more clear as to what needs to be done but haven't gotten around to it yet :sweat_smile:

**Comment by sdabhi23** [comment]
Can I take this up @systimotic?

**Comment by erictleung** [comment]
@sdabhi23 go for it!
