### ISSUE TITLE
Add "The Definitive Guide to Contributing to Open Source"

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#270]
Add to the "Useful articles for new Open Source contributors" section

Article: https://medium.freecodecamp.org/the-definitive-guide-to-contributing-to-open-source-900d5f9f2282

Add

```
- [The Definitive Guide to Contributing to Open Source](https://medium.freecodecamp.org/the-definitive-guide-to-contributing-to-open-source-900d5f9f2282) by [@DoomHammerNG](https://twitter.com/DoomHammerNG)
```

so that is appears as

- [The Definitive Guide to Contributing to Open Source](https://medium.freecodecamp.org/the-definitive-guide-to-contributing-to-open-source-900d5f9f2282) by [@DoomHammerNG](https://twitter.com/DoomHammerNG)

**Comment by AntiZERO** [comment]
I'm not at my computer at this moment but I'd like to claim this one if possible.

**Comment by jyothisankarreddy** [comment]
Hi, I can help.

**Comment by MohammadHeydari** [comment]
i can help

**Comment by erictleung** [comment]
@jyothisankarreddy @MohammadHeydari thanks for your enthusiasm. But this issue already has a pull request here https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/271. Please take a look at the other issues for other opportunities to contribute. Happy coding!
