### ISSUE TITLE
Fix typo on The Definitive Guide to Contributing to Open Source link

### ISSUE THREAD

**Issue by bismarkhenao** [freeCodeCamp/how-to-contribute-to-open-source#272]
[Link](https://medium.freecodecamp.org/the-definitive-guide-to-contributing-to-open-source-900d5f9f2282) I'm trying to create a PR but it's not possible. Thanks 👍

**Comment by erictleung** [comment]
@bismarkhenao thanks for catching this :+1:

Can you elaborate on what issues you're running into when creating a PR? I can try to help.

**Comment by bismarkhenao** [comment]
@erictleung np 👍 

I can push the changes in a new PR, seems an authentication issue. Neither SSH nor HTTPS works

**Comment by bismarkhenao** [comment]
@erictleung It's my first time as contributor, I found that all the PRs need to be done from the fork to the original. Now I've created the PR and linked with this issue.

Thanks! 👍
