### ISSUE TITLE
Add direct links to README in available languages

### ISSUE THREAD

**Issue by willamesoares** [freeCodeCamp/how-to-contribute-to-open-source#277]
What do people think about adding links to the different versions of README?

Something like adding "You can also read this in {language}" to the main README in all languages available.
I know you can access a README in a different language just by opening the file in the file tree but this is more like explicitly telling readers that we have those languages available.

Let me know if this is useful and I'll be glad to work on it.

**Comment by erictleung** [comment]
@willamesoares just merged in a PR that does just this https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/269 :smiley: Check out the [README](https://github.com/freeCodeCamp/how-to-contribute-to-open-source) now. Happy coding!
