### ISSUE TITLE
Babel/Babel website

### ISSUE THREAD

**Issue by hzoo** [freeCodeCamp/how-to-contribute-to-open-source#28]
Main Repo: https://github.com/babel/babel
Contributing: https://github.com/babel/babel/blob/master/CONTRIBUTING.md
Labels:
- https://github.com/babel/babel/labels/beginner-friendly
- https://github.com/babel/babel/labels/help-wanted

Website: http://babeljs.io/
Website Repo: https://github.com/babel/babel.github.io
Slack: https://slack.babeljs.io/
Twitter: https://twitter.com/babeljs

**Comment by erictleung** [comment]
Closed by #86.
