### ISSUE TITLE
Fix README tables in non-English README files

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#289]
Only the English `README` contains the link to the Spanish README.

So each of the non-English READMEs need the following change.

```diff
<table>
    <tr>
        <!-- Do not translate this table -->
        <td><a href="./README.md"> English </a></td>
        <td><a href="./README-CN.md"> 中文 </a></td>
        <td><a href="./README-RU.md"> русский </a></td>
        <td><a href="./README-RO.md"> Românesc </a></td>
        <td><a href="./README-IT.md"> Italiano </a></td>
+        <td><a href="./README-ES.md"> Español </a></td>
        <td><a href="./README-pt-BR.md"> Português (BR) </a></td>
    </tr>
</table>
```

The files that need changing:

- [`README-CN.md`](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/README-CN.md)
- [`README-RU.md`](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/README-RU.md)
- [`README-RO.md`](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/README-RO.md)
- [`README-IT.md`](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/README-IT.md)
- [`README-pt-BR.md`](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/README-pt-BR.md)

**Comment by marieram** [comment]
Hi @erictleung, I'd like to work on this. Are you stating that the "Espanol" line needs to be added to the files listed?

**Comment by erictleung** [comment]
@marieram hello! Yes, the "Español" lines needs to be added to all of the listed files.

For example, if you look at the English README, you see

![image](https://user-images.githubusercontent.com/2754821/52739544-022ae700-2f86-11e9-9af5-1ce28f254326.png)

But if you look at the `README-RO.md` file, you see

![image](https://user-images.githubusercontent.com/2754821/52739590-1bcc2e80-2f86-11e9-8c23-5094565a9146.png)

Additionally, if you could add this table to the [Spanish `README`](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/README-ES.md) as well, that would be fabulous! Currently, there is no table at all in that file.

Let me know if you need any more guidance or help. Thanks!
