### ISSUE TITLE
Help with the Greek translation of README

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#298]
There's an ~~open~~ closed pull request for translating the `README.md` file into Greek https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/235.

~~Please see that pull request if you are interested in helping out with that translation. Feel free to discuss changes here or at the pull request.~~ I've merged that pull request so that others can continue to contribute to it. Feel free to translate what you can. There are no expectations that you *have* to translate the entire README in one go.

**Comment by elgaspar** [comment]
Hello, i would like to help with translating. May I?

**Comment by erictleung** [comment]
@elgaspar sure! I've merged the PR already, so you just need to make changes from that file. If you do make a pull request, please refer to this issue by writing `#298` in the pull request message. Let me know if you have any other questions.

**Comment by erictleung** [comment]
Closed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/300
