### ISSUE TITLE
Add git-tips to Using Version Control section

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#305]
Add this link to the Using Version Control section

https://github.com/git-tips/tips

along with a sensible description, like the one from the repository:

> Most commonly used git tips and tricks.

**Comment by huytn12** [comment]
claimed this

**Comment by erictleung** [comment]
Closed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/310
