### ISSUE TITLE
Remove broken Waffle.io link in PROJECTS.md

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#316]
There is a broken link in the [`PROJECTS.md`](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/PROJECTS.md) file that needs to be removed. 

```diff
  - [Hoa](https://hoa-project.net) (project)
      - [Contributing Guide](https://hoa-project.net/En/Literature/Contributor/Guide.html)
      - Issue labels:
-         - [casual](https://waffle.io/hoaproject/Central?search=difficulty:%20casual)
```

More directly, [this line here around Line 52](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/PROJECTS.md#L52) needs to be deleted.

This is because [Waffle.io](https://help.waffle.io/waffle-shutdown/waffle-shutdown-tldr) is closing 😢

**Comment by sumanismcse** [comment]
Can i work on this issue?

**Comment by PoseidonSigmaX** [comment]
Pull Request created. 

@sumanismcse I might be wrong on this, but in most cases I don't think you need to ask for permission unless they specifically ask you to claim the issue first.

**Comment by sumanismcse** [comment]
Ok thanks @PoseidonSigmaX .. I didn't know.

**Comment by erictleung** [comment]
@sumanismcse @PoseidonSigmaX @tudoranghelina91 thanks for all of your enthusiasm for contributing!

@PoseidonSigmaX typically when contributing, it is courteous to check if the repository you're contributing to has a `CONTRIBUTING.md` file. This repository happens to have one [here](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/CONTRIBUTING.md#submitting-a-pull-request). Our's specifically outlines how to contribute and we ask that interested contributors claim issues first (emphasis added).

> If you decide to fix an issue, **it's advisable to check the comment thread to see if there's somebody already working on a fix**. If no one is working on it, **kindly leave a comment stating that you intend to work on it**. That way other people don't accidentally duplicate your effort. 

So it was appropriate for @sumanismcse to comment first. Hence why I've merged their pull request to the repository over @PoseidonSigmaX's. I hope you all understand.

@tudoranghelina91 as mentioned in the quoted `CONTRIBUTING.md` document, please take a look at the other pull requests that tackle the same issue. In this case, there were two other pull requests aiming to fix this issue. In your future open-source contributing endeavors, I'd advise taking a look at the current pull requests to make sure someone else hasn't tried it.

Closed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/318. Happy coding, y'all!
