### ISSUE TITLE
Add Angular 2 + Redux

### ISSUE THREAD

**Issue by dancancro** [freeCodeCamp/how-to-contribute-to-open-source#32]
Here's what I have so far. It includes re-implementations of some OSS single-feature demos into one big application. The goal is to provide learners with access to code as complete as it is in real companies without them having to get hired first.
https://github.com/dancancro/great-big-angular2-example

**Comment by vikramnr** [comment]
@erictleung  I will add this.

**Comment by erictleung** [comment]
@vikramnr please add them to the [PROJECTS.md](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/PROJECTS.md) file.

**Comment by vikramnr** [comment]
@erictleung  Have created PR.

**Comment by ravk1234** [comment]
Is the issue still open?

**Comment by bismarkhenao** [comment]
@erictleung this one was merged on #136

**Comment by erictleung** [comment]
@bismarkhenao thanks! :)
