### ISSUE TITLE
Add Drasner's article on how to contribute to open source

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#326]
Link: https://css-tricks.com/how-to-contribute-to-an-open-source-project/

This can probably go under the "Contributing to Open Source in general" section.

**Comment by sanjeev0007** [comment]
can you please check why the changes are not accepted ?

**Comment by m2paulc** [comment]
Hello! Is this issue still open? Can I help to add this link?

**Comment by amritanshu00** [comment]
#343 Hey, I added the link.

**Comment by erictleung** [comment]
Closed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/329
