### ISSUE TITLE
Structure for the repo

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/how-to-contribute-to-open-source#36]
Let's keep this issue to discuss a structure for the repo. 

Obviously, we don't want to be adding everything to the repo's Readme.md. Here are a few concepts to think of the structure, please add more as you please:

- Firstly IMHO we want this to be a dead simple resource for new contributors to either start their contributing journey and add resources in this repo as a process Or just use this as a reference to get help in starting out.
- Markdown formatted files should be a good style format for this.
- Next, we would want to segregate things into sectioned files for types of resources, like blog posts, articles, repositories, contributing guides, etc.
- Finally, and most importantly we don't want to overwhelm new contributors, with a plethora of guides.

Hope this gives an idea on how to proceed. Happy contributing!

**Comment by erictleung** [comment]
@raisedadead thanks for bringing up the structure of the repo. Just getting around to responding to it 😄 

> Finally, and most importantly we don't want to overwhelm new contributors, with a plethora of guides.

I agree that we shouldn't have too cluttered of a guide.

> Next, we would want to segregate things into sectioned files for types of resources, like blog posts, articles, repositories, contributing guides, etc.

So with all the [project](https://github.com/FreeCodeCamp/how-to-contribute-to-open-source/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Aproject) and [organization](https://github.com/FreeCodeCamp/how-to-contribute-to-open-source/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20%20label%3Aorganisation%20) resources to be added, these each should go into their each Markdown file to keep the main `README` clean.

> Firstly IMHO we want this to be a dead simple resource for new contributors to either start their contributing journey and add resources in this repo as a process Or just use this as a reference to get help in starting out.

To potentially really help out contributors at all developing levels, we could have a little section on giving different articles and resources to look into based on their coding/contributing level. So an example level would be like "You've never contibuted before but want to: ..." and under that heading, list one or two really helpful guides/resources to look into.

This might be helpful to lessen the decision effort into choosing which article would fix them best. Other levels of contributing we could have are "I've made one PR before" and "I want to find more issues to fix!".

The only issue I can see is the choosing of these couple resources for each level. At the very least, it should be a starting point to exploring all the other links in this repo.

**Comment by QuincyLarson** [comment]
I agree with @raisedadead and @erictleung that we don't want to overwhelm first-time visitors with complexity. 

We can build a static webpage front end that consumes our markdown files and makes them more searchable (maybe using something like Gatsby if it's ready for prime time). As for the structure of the main README.md, I agree that we should keep it simple and link to other pages in the repo. 

We might not even want to link to projects on the main README.md and instead point them to the web UI or an /open-source-projects directory that contains individual markdown files for each repo.

@shubheksha what do you think about this?

**Comment by erictleung** [comment]
Okay, so we can decide to use Gatsby later, but for now, I think we can just stick all the projects and organizations into one file organized similarly to how @shubheksha has laid out in https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/34


```
# Projects and Organizations

**Key**:
:o2: = organization
:package: = project
:scroll: = contributing guidelines
:label: = different issue labels

- freeCodeCamp :o2:
    - [freeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp/)
    - [Contributing guide](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) :scroll:
    - Issue label :label: :
        - [first-timers-only](https://github.com/FreeCodeCamp/FreeCodeCamp/issues?q=is%3Aopen+is%3Aissue+label%3Afirst-timers-only) 
        - [help wanted](https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)
```

Which will render to something like this

> # Projects and Organizations
> 
> **Key**:
> 
> :o2: = organization
> :package: = project
> :scroll: = contributing guidelines
> :label: = different issue labels
> 
> - freeCodeCamp :o2:
>     - [freeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp/) :package: 
>     - [Contributing guide](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) :scroll: 
>     - Issue label :label: :
>         - [first-timers-only](https://github.com/FreeCodeCamp/FreeCodeCamp/issues?q=is%3Aopen+is%3Aissue+label%3Afirst-timers-only) 
>         - [help wanted](https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)

**Comment by QuincyLarson** [comment]
@erictleung This looks excellent. I like that hierarchy. 

> - freeCodeCamp :o2:
>     - [freeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp/) :package: 
>         - [Contributing guide](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) :scroll: 
>         - Issue label :label: :
>             - [first-timers-only](https://github.com/FreeCodeCamp/FreeCodeCamp/issues?q=is%3Aopen+is%3Aissue+label%3Afirst-timers-only) 
>             - [help wanted](https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)
