### ISSUE TITLE
Hacktoberfest requires 4 PRs only

### ISSUE THREAD

**Issue by Bam92** [freeCodeCamp/how-to-contribute-to-open-source#363]
Hi!

On the date of today to be qualified for Hacktoberfest you only need to have at least 4 PRs not 5.

https://hacktoberfest.digitalocean.com/

**Comment by erictleung** [comment]
@Bam92 thanks for catching this. Looks like they've changed in from their past offer.

**Comment by jaherche** [comment]
I would like to work on this for the english README.md if it is still available.

**Comment by jaherche** [comment]
I have submitted a PR for this issue. This is my first (ever), so I am glad to take any and all feedback.
