### ISSUE TITLE
Add "Getting into Open Source for the First Time"

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#37]
Very extensive post by Dean McDonnell on step-by-step process to contributing to projects.

Probably good under the ["Useful articles for new open source contributors"](https://github.com/FreeCodeCamp/how-to-contribute-to-open-source#useful-articles-for-new-open-source-contributors) section.

Article: http://www.nearform.com/nodecrunch/first-time-with-open-source/

**Comment by morrme** [comment]
Hi, there seem to be a few issues with links that you want added to the same page. Is it  OK to add them in one PR?

**Comment by erictleung** [comment]
@morrme I would be okay with addressing a couple issues in one PR, but don't go too crazy and add all the links 😉

**Comment by mmcewan** [comment]
@erictleung - If this issue is still open I'd like to take it.

**Comment by erictleung** [comment]
@mmcewan go for it! :+1:
