### ISSUE TITLE
Translate ReadMe to Arabic

### ISSUE THREAD

**Issue by kaliomar** [freeCodeCamp/how-to-contribute-to-open-source#386]
I want to make an Arabic README.md.

**Comment by erictleung** [comment]
@kaliomar go for it! Take a look at the other translations in this repository for examples of how to format things. Also, I do not know Arabic, so after you've created a pull request to this repository, try to get someone else who knows Arabic to review your translation. 

Please name this new translation file `README-AR.md`. Feel free to post any questions here! Good luck!

**Comment by radiasl** [comment]
@kaliomar still working on this? I'd like to give it a try if not

**Comment by erictleung** [comment]
@radiasl go for it if you're up for it! Let me know if you have any questions about helping 👍

**Comment by GaroK01** [comment]
I can also help you guys. (if you still need help)

**Comment by erictleung** [comment]
@GaroK01 yep, it looks like this issue is still open, so feel free to take this translation! :+1:

**Comment by MohamdAlhawi** [comment]
me too I can help here, I'd love to do that 😊

**Comment by erictleung** [comment]
@MohamdAlhawi great!

There currently is no `README-AR.md` file so anyone can feel free to start a pull request. You don't have to finish all the translation. Feel free to create a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/) and others can help review it along the way. You can also [make suggestions](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/incorporating-feedback-in-your-pull-request#applying-a-suggested-change) within pull requests that will count as contributions as well.

**Comment by MohamdAlhawi** [comment]
> @MohamdAlhawi great!
> 
> There currently is no `README-AR.md` file so anyone can feel free to start a pull request. You don't have to finish all the translation. Feel free to create a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/) and others can help review it along the way. You can also [make suggestions](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/incorporating-feedback-in-your-pull-request#applying-a-suggested-change) within pull requests that will count as contributions as well.

I'll do that thanks

**Comment by khali70** [comment]
I would be happy to be a part in such a great project @erictleung  @kaliomar

**Comment by erictleung** [comment]
@khali70 great! Take a look at the open pull request [here](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/457) and review the translation to see if it makes sense and retains its original meaning. Thanks!

**Comment by GAbdulwahab** [comment]
i want to translate

**Comment by GAbdulWahab** [comment]
can I help to translate to Arabic with them @erictleung @HishamKhdair @kaliomar

**Comment by erictleung** [comment]
Closed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/670 Happy coding!
