### ISSUE TITLE
Nodehawk: Testing, feedback and examples

### ISSUE THREAD

**Issue by samrith-s** [freeCodeCamp/how-to-contribute-to-open-source#389]
Hey,

I have a project called Nodehawk. 

https://github.com/samrith-s/Nodehawk

I’m looking for people to test it out and give feedback on it. Also for people who can spin up simple examples!

Do try it out and respond here or create an issue, and I’d be happy to entertain any questions and welcome any contributions or ideas!!

**Comment by samrith-s** [comment]
Labels: Newbie friendly, help wanted

**Comment by rajat641** [comment]
Hi Samrith, 
I can take this task and help on this.

**Comment by samrith-s** [comment]
Hey @rajat641, I’d be happy to assist you! Can you create an umbrella issue on any thing you want to work on? Alternatively, you can reach out to me on [twitter](twitter.com/tueieo).

**Comment by shivaramayysola** [comment]
Hi Samrith 
I am interested to help you. I can take this issue and work on this. Please let me know.

**Comment by samrith-s** [comment]
Hey @shivaramayysola 👋 definitely! Let me know if you need any help!

**Comment by AsswinCR** [comment]
Hello Samrith,
 I am interested to help you with this task, can you guide me, what is to be done :)?

**Comment by adityadalwadi1510** [comment]
Hello, Samrith!
I'm eager to assist you with your task. Could you please provide me with some guidance on what needs to be done? I'm here to help!

**Comment by DanielsWebDevelopment** [comment]
Hello, Samrith, I
'd love to be of assistance on this project, is it still open?

**Comment by aabidraina6** [comment]
This is a test comment **Please Ignore**

**Comment by rahulray8516** [comment]
Hello, Samrith, I would love to assist with your task. Is it still open ?

**Comment by erictleung** [comment]
Closing as this project doesn't appear to be active anymore. Happy coding!
