### ISSUE TITLE
Add 45 GitHub Issues Dos and Don'ts

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#39]
The article is about:

- Reporting issues
- Requesting features
- Pull requests
- Being a decent human being

Not directly involved in "contributing" to an open source project but I think it has some good tips for interacting with one.

This could be stashed in a "Miscellaneous" section.

Source: https://hackernoon.com/45-github-issues-dos-and-donts-dfec9ab4b612#.2rqkbkp3g

**Comment by Elysei** [comment]
Hi, I'm new to contributing (and to git/github) but I think I have enough understanding to do this.

**Comment by erictleung** [comment]
@Elysei thanks for your interest! Feel free to visit the [contributors Gitter chat room](https://gitter.im/FreeCodeCamp/Contributors) for help with git and GitHub if you need it. Or feel free to message me on Gitter as well. Good luck!

**Comment by erictleung** [comment]
Closing as fixed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/69.
