### ISSUE TITLE
Broken links in CONTRIBUTING failing Travis

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#393]
In our [`CONTRIBUTING.md` file](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/CONTRIBUTING.md), there are some links that are being read into our link checker to make sure it is valid. However, I put in dummy links for an example.

![Image of three links failing Travis tests](https://user-images.githubusercontent.com/2754821/80815690-fa536480-8b82-11ea-9f98-e7d83b81f638.png)

Let's update this to have actual content.

Please change those links in the CONTRIBUTING.md file to something like this (remove the top original content in red with the lower content in green):

```diff
- - [Project name](https://github.com/project-name/proj) (project)
-     - [Contributing Guide](https://github.com/project-name/proj/blob/master/CONTRIBUTING.md)
-     - Issue labels:
-         - [Good First Issue](https://github.com/project-name/proj/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)
+ - [freeCodeCamp](https://www.freecodecamp.org/) (org)
+     - [freeCodeCamp](https://github.com/freeCodeCamp/freeCodeCamp/) (project)
+         - [Contributing guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md)
+         - Issue labels:
+             - [first-timers-only](https://github.com/FreeCodeCamp/FreeCodeCamp/issues?q=is%3Aopen+is%3Aissue+label%3Afirst-timers-only)
```

There is one other link that is failing Travis from the Linux Foundation, but that can be left alone for now as a different issue.

**Comment by rajat641** [comment]
Hi Eric,
I can take this task.

**Comment by erictleung** [comment]
@rajat641 sorry, but it looks like someone else has already created a pull request a couple days https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/397.

**Comment by erictleung** [comment]
Closed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/397
