### ISSUE TITLE
HTTP 502 error in Travis

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#394]
One link in the [`README-CN.md` file](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/README-CN.md) is causing an issue.

![Image of broken link in Travis with 502 error](https://user-images.githubusercontent.com/2754821/80818688-87e58300-8b88-11ea-917d-0d0e189e5257.png)

I think the easiest way to deal with this is to add `502` to our "acceptable" responses. I don't imagine this happening a lot. The link itself (https://www.linuxfoundation.org/resources/open-source-guides/) still works. But for whatever reason, it cannot be pinged.

We can update this in the [`package.json` file](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/package.json) with the following.

```diff
- "test": "awesome_bot *.md --allow-redirect --allow-ssl --allow-dupe --allow 429",
+ "test": "awesome_bot *.md --allow-redirect --allow-ssl --allow-dupe --allow 429,502",
```

**Comment by Uneetpatel7** [comment]
Hello! I am new to open source. I would love to pick this up

**Comment by erictleung** [comment]
@Uneetpatel7 great! It's yours. Let me know if you have questions or need help making the change.

**Comment by Uneetpatel7** [comment]
Please check the PR! @erictleung

**Comment by erictleung** [comment]
Closed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/395
