### ISSUE TITLE
Add "Contributing to Open Source on GitHub" article

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#40]
Article could be put in the [Useful articles for new open source contributors](https://github.com/freeCodeCamp/how-to-contribute-to-open-source#useful-articles-for-new-open-source-contributors) section.

**Outline:**

- Intro
- Find Projects
- A Typical Project
- Contributing to a Project

Source: https://guides.github.com/activities/contributing-to-open-source/index.html

**Comment by Toughee** [comment]
Hi. I can help with this issue.

**Comment by erictleung** [comment]
@Toughee go for it! :+1:

**Comment by Toughee** [comment]
I'm finishing the draft right now.

I should send everything done by this weekend.

**Comment by Toughee** [comment]
It's done. Here's the article's link:
http://tougheestech.blog/2017/05/22/how-to-contribute-to-open-source-on-github/

Is there's anything you see that I need to fix or add to the article before I commit any changes?

**Comment by erictleung** [comment]
@Toughee thanks for taking the time to write the article. If it wasn't clear on what the issue was, it was to add the link I posted to the [README.md](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/README.md) file. If you're still interested in adding it to the list, feel free to do so and let me know if you have any questions about it.

**Comment by erictleung** [comment]
Closed by #52
