### ISSUE TITLE
Help translate README to Bulgarian

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#405]
In progress PR https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/382. See progress and review this PR if you know Bulgarian.

**Comment by yogeshsingh2672000** [comment]
I am pleased to do it.
Thank you

**Comment by yogeshsingh2672000** [comment]
i wanted to do it

**Comment by erictleung** [comment]
@yogeshsingh2672000 great! There's already a pull request for it. Please take a look at it so you don't have duplicate work. You can review the PR here https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/382/files. If there are too many changes that need to be made, feel free to create a new pull request. You can also make [suggested edits to the current PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/incorporating-feedback-in-your-pull-request#applying-a-suggested-change) and your contributions will be added.

Let me know if you have any questions.

**Comment by janvig** [comment]
Hey @erictleung, can I use Google Translate API? I tried it with English <=> German and worked pretty good.

**Comment by erictleung** [comment]
@janvig feel free to do so. However, we should get a native speaker to double check it.

**Comment by erictleung** [comment]
@janvig once you've converted it with Google Translate, feel free to compare the current translation with using the suggest function on GitHub https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/382/files

**Comment by janvig** [comment]
Hey @erictleung, I thought of validating the existing translation and improving it, rather than producing a new text and repeating the process. So I got a person from Bulgaria to read the translated text in here https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/382/files and all seems fine.

**Comment by erictleung** [comment]
Closed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/382
