### ISSUE TITLE
Translate README.md to Hindi

### ISSUE THREAD

**Issue by dipscodehub** [freeCodeCamp/how-to-contribute-to-open-source#410]

**Comment by dipscodehub** [comment]
@erictleung @QuincyLarson I want to translate the README.md file in Hindi and contribute to this Project. 
what are the things I should keep in mind can you please help me regarding this.

**Comment by erictleung** [comment]
@dipscodehub thanks for your interest in contributing! To be as accurate as possible, it would be great if you could also get another person who speaks Hindi could review your pull request changes. If you cannot, then we can just leave the pull request there until someone else can. 

Otherwise, I would follow the main English `README.md` as best as possible. Let me know if you have any other questions.

**Comment by dipscodehub** [comment]
@erictleung sure I'll get someone to review the hindi version of the readme file.
Is there and eligibility for the person who is going to review the readme

**Comment by dipscodehub** [comment]
@erictleung and please add the badge of in progress or assign this to me as I've already started the translation and have completed half of the readme

**Comment by erictleung** [comment]
> 
> 
> @erictleung sure I'll get someone to review the hindi version of the readme file.
> Is there and eligibility for the person who is going to review the readme

The only requirement is that they also understand Hindi enough to verify your translation and give any feedback on changes if they see any.

Thanks!

**Comment by Lucky0108** [comment]
Hey Guys, I was looking to do open source contribution. And I came across this Issue. I would like to tell you that I also speak Hindi and that I can help @dipscodehub in reviewing the Hindi translation of Readme.md if needed. 

Thanks!

**Comment by dipscodehub** [comment]
@Lucky0108 Once i complete the translation I'll ping you to review the file.

**Comment by Lucky0108** [comment]
Sure!

**Comment by KhushiGangopadhyay** [comment]
hey guys , even i speak hindi and i think i can help in reviewing the translation :)

**Comment by KhushiGangopadhyay** [comment]
Thank you for informing,I would like to contribute to the channel, please
can you tell what are the next steps?

**Comment by erictleung** [comment]
@dipscodehub @KhushiGangopadhyay take a look at our contributing page to find ways to help out https://contribute.freecodecamp.org/ Thanks for your interest!

**Comment by Deek9399** [comment]
I would like to be a contributor for this issue. 
@dipscodehub Let me know if I could help with something.
Thanks

**Comment by erictleung** [comment]
@Deek9399 thanks for your interest! It doesn't look like there's an open pull request with changes yet. So you can feel free to start translating and just comment here for help on double-checking the translation with someone else. 

If you need help on how to start this translation, you can take a look at the contributing document https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/CONTRIBUTING.md

**Comment by vivek80801** [comment]
@erictleung
  
I want to conntribute to freecodecamp. What are ways in which I can contribute to freecodecamp?
It will be great if I can contribute to freecodecamp.

Can I also try to translate README.md into Hindi ?

Thank You.

**Comment by erictleung** [comment]
@vivek80801 welcome! In general, here are ways you can help out https://contribute.freecodecamp.org/

It appears someone has already translated the README to Hindi https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/462. You can help contribute by reviewing their translation and ensuring it is accurate.

You can receive credit and make suggestions on this page https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/462/files You can read more about code review [here](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews#about-pull-request-reviews).

**Comment by Avinash-Gahlowt** [comment]
@erictleung I just really want to contribute to freecodecamp since i have been learning a lot from its youtube  channel really wanted to work for it. Can you guide me some.

**Comment by ieahleen** [comment]
@Avinash-Gahlowt : it's awesome you want to contribute to freeCodeCamp! you can start reading contribute.freecodecamp.org

**Comment by Jeevan-Kiran-Lenka** [comment]
Heya! I can help in double-checking the Hindi readme and also if possible to add the required changes to it

**Comment by arhaan023** [comment]
Hi, I speak Hindi too, and I really want to contribute here in translation, but I see this branch is closed right now. How can I still contribute here?

**Comment by Shashwat-05** [comment]
what's the issue here, why does Hindi Readme file not been merged yet ?? Does it need updating? If so, I can assist.

**Comment by kunalkumar007** [comment]
Hello @erictleung, I am a native Hindi speaker too. Hope if I can help to close this issue.

**Comment by IMPranshu** [comment]
@dipscodehub Hello I am a native Hindi Speaker and I really want to contribute in converting the readme to Hindi language

**Comment by erictleung** [comment]
Hi everyone! Thanks for everyone's interest. I just merged in a PR that many have contributed to https://github.com/freeCodeCamp/how-to-contribute-to-open-source/issues/410. I'll be closing this issue, but feel free to read through the changes and make suggestions through a PR. Thanks again everyone for those who helped! Happy coding!
