### ISSUE TITLE
Add Ovio to the section "Contributing to Open Source in general"

### ISSUE THREAD

**Issue by tiphaineboyer** [freeCodeCamp/how-to-contribute-to-open-source#418]
Hi, I'd like to add [ovio.org](https://ovio.org) to the list of options proposed in your README. 
Ovio is on the mission to empower more developers to contribute to open source projects. We created a [platform](https://explore.ovio.org) with a curated and personalized selection of open source projects to accelerate contributors matching. This platform makes it easy for developers to find the right open source tasks and get involved in a project while providing maintainers the tools to attract tech talent and build their communities.
One of its particularities it's the [issue search](https://explore.ovio.org/projects) that allows developers to get matched with a specific issue.
I hope this community will find our tool useful and add it to the list of solutions for first-time contributors.

**Comment by itisdb** [comment]
I would like to take it up.

**Comment by erictleung** [comment]
@itisdb great! Take a look at our [contributing](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/CONTRIBUTING.md#adding-to-the-project-file) document here for how to add open-source projects :+1:

**Comment by erictleung** [comment]
Closed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/486
