### ISSUE TITLE
Danger secrets not set up?

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#438]
From the last PR, here is the GitHub Actions output https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/434/checks:

```
Could not set up API to Code Review site for Danger

For your GitHub repo, you need to expose: DANGER_GITHUB_API_TOKEN
```

cc/ @raisedadead

**Comment by raisedadead** [comment]
Thanks for merging those PRs Eric, and this is a weird one. 

I did test it before and it was working in an initial PR: #431, where the bot did comment.

But I can see that the CI is errored in a later PR here: https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/434/checks#step:4:230 and the interestingly it has found them in the list of ENV: https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/434/checks#step:4:233 

![image](https://user-images.githubusercontent.com/1884376/94991137-93593200-059e-11eb-9fa7-efa4df5ebfd7.png)

I will investigate.

**Comment by raisedadead** [comment]
Looks like I will be needing to switch back to the danger-js stack instead. For now I have disabled danger and defaulting to an error-ed status on awesome_bot

The goal was to catch duplicated and broken links as comments on the PR, and even check the translated files, leave an automatic comment for a peer review, and comment for common mistakes.

I will circle around to getting this done hopefully over the weekend.

**Comment by erictleung** [comment]
Thanks for submitting those changes though! I'm still new at GitHub actions but it seems helpful. I did notice it working for a bit (as you pointed out).

Take your time, this is a pretty low-priority bug, but I appreciate your help on it. I saw what [danger-js](https://danger.systems/js/) can do and I think it would be helpful :+1: Thanks!

**Comment by raisedadead** [comment]
The actions when coupled with the ruby binaries in the bash env for actions are orders of magnitude faster. I am new to Danger itself, and currently investigating the issue which basically boils down to:

If a change was made on a branch on the parent repo and followed by a PR to any branch on the parent repo, the setup works.

It breaks when the same is done for a PR on the fork.

**Comment by erictleung** [comment]
Yeah, I came to a similar conclusion based on the output from your debug PR checks https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/440/checks

```
From freeCodeCamp/how-to-contribute-to-open-source
 * [new branch]      master     -> origin/master
fatal: Couldn't find remote ref refs/heads/test-actions
fatal: Couldn't find remote ref refs/heads/test-actions
fatal: Couldn't find remote ref refs/heads/test-actions
fatal: Couldn't find remote ref refs/heads/test-actions
bundler: failed to load command: danger (/usr/local/bundle/bin/danger)
RuntimeError: Commit 8fcb7195 doesn't exist. Are you running `danger local/pr` against the correct repository? Also this usually happens when you rebase/reset and force-pushed.
```

**Comment by RandellDawson** [comment]
@raisedadead Everything I had ever read about Danger was that it was not recommend for forked repos.

**Comment by raisedadead** [comment]
> Everything I had ever read about Danger was that it was not recommend for forked repos.

I do not think that's accurate, see `https://github.com/vsouza/awesome-ios/pull/1001`, and their Dangerfile is quite minimal the only difference is they are on Travis.

With GitHub actions there is something called as `pull_request_target` (instead of the normal `pull_request`) event that is meant to address the "context" of execution, but neither `danger-js` nor `danger` supports it natively as of now.

There are some ongoing discussions on their repo though. 

I am exploring [other actions that use a simple commenting approach](https://github.com/peter-evans/create-or-update-comment), but I did not want to write and maintain JS code for our logic to parse display the results generated by `awesome_bot`.

**Comment by raisedadead** [comment]
Out of the scope of my limited time.
