### ISSUE TITLE
list of beginner-friendly FOSS projects

### ISSUE THREAD

**Issue by pdurbin** [freeCodeCamp/how-to-contribute-to-open-source#44]
Hi! I just read "I am trying to create a list of beginner-friendly FOSS projects" at https://medium.freecodecamp.com/how-to-attract-new-contributors-to-your-open-source-project-46f8b791d787#.jrgxexd14 and it's unclear to me where to find this list in this repo.

I see that a heading in the README called "Open Source Projects to contribute to:" followed by a list of projects has been proposed in pull request #23. Are there other ideas being considered? Is the goal still to create a list of beginner-friendly FOSS projects?

p.s. I'm listening to http://www.codenewbie.org/podcast/open-source-newbie right now and it's fantastic.

**Comment by erictleung** [comment]
@pdurbin thanks for the issue. Yeah, we've been trying to figure out the directory structure to save that list in. For now, you can check out the ["project"](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/issues?q=is%3Aissue+is%3Aopen+label%3Aproject) labeled issues for some ideas.

**Comment by ayanujju** [comment]
Can I work on this issue ?

**Comment by pdurbin** [comment]
@ayanujju I see that @erictleung added a "help wanted" label so I assume it's fine for you (or others reading this) to work on this issue. :smile:

**Comment by lyndel2** [comment]
Hi  there , Please can I contribute to this issue?

**Comment by erictleung** [comment]
@lyndel2 thanks for commenting! Yes, feel free to take on this issue. Let us know if you have any or need any help contributing :+1:

**Comment by DeVil2O** [comment]
Is this issue has solved out or can I take this issue?

**Comment by pdurbin** [comment]
@DeVil2O I believe you can take this issue. Thanks!

**Comment by DeVil2O** [comment]
@pdurbin Ok.

**Comment by pawki07** [comment]
Hey there! Can I contribute to this project.

**Comment by erictleung** [comment]
@pawki07 thanks for your interest! This issue was unclear in the past because there was no projects file to contribute to. We have one right now. I will update the CONTRIBUTED.md file for more information on this file instead of relying on this issue here. Happy coding!
