### ISSUE TITLE
Replace blog link with more stable link

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#447]
[This link](https://www.hanselman.com/blog/bring-kindness-back-to-open-source) recently was flagged for "misbehaving" on an `awesome_bot` check. This article is sufficiently old that we can probably use a more permanent link for it (https://web.archive.org/web/20201009150545/https://www.hanselman.com/blog/bring-kindness-back-to-open-source)

Here's the change I'm proposing:

```diff
- - [Bring Kindness Back to Open Source](https://www.hanselman.com/blog/BringKindnessBackToOpenSource.aspx) by [@shanselman](https://github.com/shanselman) 
+ - [Bring Kindness Back to Open Source](https://web.archive.org/web/20201009150545/https://www.hanselman.com/blog/bring-kindness-back-to-open-source) by [@shanselman](https://github.com/shanselman)
```

This line is here https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/README.md#L92

**Comment by ImagineZero0** [comment]
Can I work on this?

**Comment by erictleung** [comment]
@ImagineZero0 go for it!

**Comment by ImagineZero0** [comment]
I have forked, cloned and changed the readme.md file in the repo respectively and made the push origin or pull request..
Please verify it..

**Comment by erictleung** [comment]
@ImagineZero0 great! I see that you've made updates on your own fork https://github.com/ImagineZero0/how-to-contribute-to-open-source/commit/975b66976ba3b3dcbf82c80e20d04a24219cb767.

The next step is to then make a pull request to this repository https://github.com/freeCodeCamp/how-to-contribute-to-open-source/compare. When you visit the page, GitHub should have some points around the page suggesting making a pull request that should make it easier to make a pull request to make the changes here.

You can also follow this tutorial on making a pull request https://yangsu.github.io/pull-request-tutorial/

I hope that helps. Thanks!

**Comment by ImagineZero0** [comment]
I think I have now been able to make a PR on the main repository and therefore please verify those changes.

Thank you very much for your help and this helped me really understand how to contribute to open source

**Comment by erictleung** [comment]
Resolved by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/453
