### ISSUE TITLE
Update ignore list

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#448]
This issue has two parts/files to address.

The ignore list in our [`test.yml` file](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/.github/workflows/test.yml) can be updated by removing information for `kentcdodds`, which we will address in the secdon part of this issue.

```diff
- awesome_bot -f README.md --allow-ssl --allow 302,429 --white-list firsttimersonly.com,github.com/github,creativecommons.org/licenses/by-sa/4.0,@kentcdodds,kentcdodds.com/blog/what-open-source-project-should-i-contribute-to
+ awesome_bot -f README.md --allow-ssl --allow 302,429 --white-list firsttimersonly.com,github.com/github,creativecommons.org/licenses/by-sa/4.0
```

Line of code that needs to be changed: https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/.github/workflows/test.yml#L22

The information for `kentcdodds` can be removed because we need to fix the link that is being ignored with a trailing forward slash at the end of the website.

```diff
- - [What open-source should I contribute to](https://kentcdodds.com/blog/what-open-source-project-should-i-contribute-to) by Kent C. Dodds
+ - [What open-source should I contribute to](https://kentcdodds.com/blog/what-open-source-project-should-i-contribute-to/) by Kent C. Dodds
```

Line of code that needs to be changed: https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/README.md#L105

**Comment by sonylomo** [comment]
Please assign this to me. 😁

**Comment by sonylomo** [comment]
I've forked and made a PR: I carefully followed your instructions, but a check failed.
This is my first time. 😅

**Comment by erictleung** [comment]
@sonylomo no worries! That's another issue 😄 

Closing as resolved by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/450

**Comment by sonylomo** [comment]
Thanks @erictleung
