### ISSUE TITLE
Replace author website because no longer available

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#449]
The site http://www.letakeane.com/ is no longer available. Their Twitter page is also not active. So let's replace their page with their Hacker Noon page instead https://hackernoon.com/u/letakeane

```diff
- - [A junior developer’s step-by-step guide to contributing to Open Source for the first time](https://hackernoon.com/contributing-to-open-source-the-sharks-are-photoshopped-47e22db1ab86) by [@LetaKeane](http://www.letakeane.com/)
+ - [A junior developer’s step-by-step guide to contributing to Open Source for the first time](https://hackernoon.com/contributing-to-open-source-the-sharks-are-photoshopped-47e22db1ab86) by [@LetaKeane](https://hackernoon.com/u/letakeane)
```

Line of code to change: https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/README.md#L101

**Comment by cBridges851** [comment]
Can I be assigned to this issue please?

**Comment by erictleung** [comment]
@cBridges851 go for it! Let me know if you have any questions about changing things :+1:

**Comment by cBridges851** [comment]
Thank you @erictleung 😄

**Comment by cBridges851** [comment]
A pull request has been made 😀

**Comment by erictleung** [comment]
@cBridges851 great, thanks!

Closing issue as resolved by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/451
