### ISSUE TITLE
Translate the Guide to INDONESIAN

### ISSUE THREAD

**Issue by YosephKS** [freeCodeCamp/how-to-contribute-to-open-source#459]
Hey, I am trying to start doing some small open source contributions and I think translating the guide to Indonesian would be a great start. Do you think I can get the approval to do so?

**Comment by erictleung** [comment]
@YosephKS go for it! Thanks for your interest in helping out.

When making the file, please name it `README-ID.md`. Take a look at our contributing documentation if you have any questions about contributing https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/CONTRIBUTING.md.

**Comment by YosephKS** [comment]
@erictleung you can check the PR here: https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/467.

Let me know if there is anything that I need to revise. Thank you.

**Comment by erictleung** [comment]
@YosephKS thanks! Sorry for the late response. I got busy with some other work. I made some comments on your pull request :+1:

**Comment by erictleung** [comment]
Closed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/467
