### ISSUE TITLE
Add GitHub Guides to "Using version control" section

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#46]
## Requested Changes

Add underneath this section https://github.com/freeCodeCamp/how-to-contribute-to-open-source#contributing-to-open-source-in-general

Source: https://guides.github.com/

## Contributing Help

Follow the directions below if you want to work on this on the command line. Otherwise, following the instructions in the Contributing document.

You'll want to fork this project first by clicking on the button on the top right corner that says "Fork".

Then in your terminal type the following

```
git clone https://github.com/yourUserName/how-to-contribute-to-open-source.git
cd how-to-contribute-to-open-source
git checkout -B add-github-guides
... # Make changes to README.md
git add README.md
git commit -m "Added GitHub Guides"
git push origin add-github-guides
```

Then go to your fork and you should see a message about making a pull request.

If you have any questions, let me know and I can give you assistance. Good luck!

**Comment by vikramnr** [comment]
@erictleung Is this being done?

**Comment by vikramnr** [comment]
@sblasa  I have raised PR from | ab86b1f | above commit but it has some conflicts So Please continue 👍

**Comment by erictleung** [comment]
@sblasa hi there! As it is already mentioned above, @vikramnr already made a pull request, but it appears your fork is not up to date, so that's why there are some conflicts. You're more than welcome to make the changes. 

Take a look at the [contributing document](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/CONTRIBUTING.md) for some help. You'll want to fork the project and if you're willing to do command line contributing, take a look at the code I put above. As always, let me know here or [on Gitter](https://gitter.im/erictleung) if you have questions. There's also the [contributor's room](https://gitter.im/FreeCodeCamp/Contributors) as well.

**Comment by sblasa** [comment]
@erictleung Hi, @vikramnr said I can to take over. It was his pull request that had some conflicts. I will do the pull request. I had forked the project already. I hope that's okay. Thanks!

**Comment by erictleung** [comment]
Closing as resolved by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/76. Happy coding!
