### ISSUE TITLE
Translate the README.MD to Ukrainian

### ISSUE THREAD

**Issue by vromaniv** [freeCodeCamp/how-to-contribute-to-open-source#469]
Hello, guys.

I'm a native Ukrainian speaker and I would like to create the _README-UK.MD_ file for this project. This seems like a great way for me to start contributing to the open-source.

If you are okay with this idea, I can start implementing the changes right away and open a PR once I'm done.

**Comment by erictleung** [comment]
@vromaniv sorry for the late response, but you're welcome to translate if you have the time and wish to! 👍 

And yes, please name your file `README-UK.md`.

**Comment by derelif** [comment]
@erictleung hello! 
As I see there are no README-UK.md yet. I would like to take part and translate README file into ukrainian
