### ISSUE TITLE
Add GitHub's Open Source Guide article, "How to Contribute to Open Source"

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#47]
Add underneath this section https://github.com/freeCodeCamp/how-to-contribute-to-open-source#contributing-to-open-source-in-general

Source: https://opensource.guide/how-to-contribute/

**Comment by lucasbarross** [comment]
I sent a pull request with the changes.

**Comment by erictleung** [comment]
@lucasbarross thanks! I've merged it. Next time, you can close issues by adding `Closes #9` or whatever issue number to the pull request body.

Fixed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/49. Closing as resolved. Happy coding!
