### ISSUE TITLE
Translate the README.md to Hebrew

### ISSUE THREAD

**Issue by Immanuelbh** [freeCodeCamp/how-to-contribute-to-open-source#470]
Hi, 
I'd like to get in to contributing to open source. 
Is there any interest in translating the readme guide to Hebrew?
I'm a native English and Hebrew speaker and would gladly help.

**Comment by erictleung** [comment]
@Immanuelbh thanks for your interest!

If you want to start the translation, please name your translation file as `README-HE.md` so it matches the ISO 639-1 convention (https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes).

**Comment by Immanuelbh** [comment]
@erictleung Thank you for the reply, I will!

**Comment by SoloNoah** [comment]
hey Immanuel, do you need any help with translating to hebrew by any chance?

**Comment by Immanuelbh** [comment]
> hey Immanuel, do you need any help with translating to hebrew by any chance?

Hi!
I'm hoping to finish the translation by next week. If I'm not mistaken for the PR to be merged the readme should be reviewed by someone else (other than me). It would be great if you could review my translation once I'm done and we could fix it together! :)

**Comment by SoloNoah** [comment]
cool :) i would gladly review it!
good luck!

**Comment by Immanuelbh** [comment]
@SoloNoah PR is up for review! Would love your help with #487

**Comment by SoloNoah** [comment]
@Immanuelbh Thanks for the update! Good job!
I will try reviewing it by Wednesday (18/11).

**Comment by SoloNoah** [comment]
I submitted a review. Sorry for the delay! Had a busy week.
