### ISSUE TITLE
Help review the Polish translation of the README.md

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#479]
We have [an open pull request](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/460) to translate our README.md to Polish. We need an additional person to review the changes for accuracy.

Feel free to make [in-line comments and suggestions](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/commenting-on-a-pull-request#adding-line-comments-to-a-pull-request) directly to the pull request. If you make use of the suggestions button, your changes are more likely to be added as commits themselves and you will get credit for those changes.

**Comment by michal-dbrnowski** [comment]
I have reviewed the original text in Polish and its changes, I think it is good now.

**Comment by erictleung** [comment]
Closing as QA is finished. Thanks @michal-dbrnowski!
