### ISSUE TITLE
Help review README.md in Malay language

### ISSUE THREAD

**Issue by EugeneGohh** [freeCodeCamp/how-to-contribute-to-open-source#482]
- Translate README.md to Malay

**Comment by EugeneGohh** [comment]
### Help me review my translation in Malay language.

>- https://github.com/EugeneGohh/how-to-contribute-to-open-source/blob/master/README-MALAY.md

**Comment by erictleung** [comment]
@EugeneGohh thanks for your translation!

I don't know Malay so I can't properly review it. I'll leave this up for others to help out.

But two quick notes on your translation:

- Please rename your file from `README-MALAY.md` to `README-MS.md` based on the two ISO 639-1 https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
- Please create a pull request to this repository with your changes. If you [click here](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pulls), you should be able to make a pull request to this repository so that we can more easily review your translation.

Thanks!

**Comment by EugeneGohh** [comment]
> @EugeneGohh thanks for your translation!
> 
> I don't know Malay so I can't properly review it. I'll leave this up for others to help out.
> 
> But two quick notes on your translation:
> 
> * Please rename your file from `README-MALAY.md` to `README-MS.md` based on the two ISO 639-1 https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
> * Please create a pull request to this repository with your changes. If you [click here](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pulls), you should be able to make a pull request to this repository so that we can more easily review your translation.
> 
> Thanks!

@erictleung Alright sure mate.I have already renamed my file and created a pull request on it.

**Comment by EugeneGohh** [comment]
@erictleung I am quite new to contribution actually.May I know what it takes to be a contributor of this?

**Comment by ieahleen** [comment]
@EugeneGohh contribute once to the repository with a PR and you become a contributor :)

**Comment by EugeneGohh** [comment]
> @EugeneGohh contribute once to the repository with a PR and you become a contributor :)

Thanks for your reply. Lovely, just learned new thing. Thank you. 🙏

**Comment by erictleung** [comment]
@EugeneGohh great thanks for your pull request https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/483!

I've labeled the pull request that it is open for review for someone else to check your translation. If you're able to find someone who also speaks and reads Malay, that would be great to help review your pull request :+1:

**Comment by RezaPurut** [comment]
@EugeneGohh  I have reviewed #483 and there are few things that need to be fixed. Anyway, good job for translating it to Malay.

**Comment by EugeneGohh** [comment]
> @EugeneGohh I have reviewed #483 and there are few things that need to be fixed. Anyway, good job for translating it to Malay.

Thank you for reviewing my Malay translation. 😊 🙏

**Comment by erictleung** [comment]
Closed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/483
