### ISSUE TITLE
Translate the README.md file to Bengali

### ISSUE THREAD

**Issue by ahammadshawki8** [freeCodeCamp/how-to-contribute-to-open-source#492]
✔✔ I am looking forward to translating the README.md file to Bengali. Feel free to suggest to me how to make my work better.

By the way,  Bengali has been ranked the sweetest of all languages in the world. So, I think it would be great if the README.md file is translated into the sweetest language.

**Comment by ahammadshawki8** [comment]
I have completed the task of translation into Bengali. Now, I am pushing the request. Eagerly waiting for your pull request.

**Comment by RohanSengupta326** [comment]
>I have completed the task of translation into Bengali. Now, I am pushing the pull request. Eagerly waiting for your pull request.

I was exploring this repository thinking I should translate the `Readme.md` file in **Bengali**, then suddenly saw it was already done. I was surprised. Great work !!

**Comment by texas2010** [comment]
I closing this issue. it seems it is done to translate.
