### ISSUE TITLE
Help review Bengali translation

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#496]
If you have working knowledge or are fluent in Bengali, we need help reviewing the translation https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/493.

Related https://github.com/freeCodeCamp/how-to-contribute-to-open-source/issues/492

**Comment by Jeevan-Kiran-Lenka** [comment]
Heya! I'm a native Bengali speaker from India and I'm working and reviewing your's Bengali readme

**Comment by erictleung** [comment]
Closed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/493
