### ISSUE TITLE
Translate README.MD to Marathi

### ISSUE THREAD

**Issue by rajnandini-tambavekar** [freeCodeCamp/how-to-contribute-to-open-source#497]
I know Marathi language , can I translate it Marathi. If it is ok please help me out with program , I'm beginner .

**Comment by praj9719** [comment]
I have recently translated  README in marathi you can check it out [here](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/499) or visit [README-MR.md](https://github.com/praj9719/how-to-contribute-to-open-source/blob/master/README-MR.md)

**Comment by erictleung** [comment]
@rajnandini-tambavekar great! Yes, it appears @praj9719 has made the translation and made a pull request https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/499. You can help contribute by reviewing the translation and making suggestions if there needs to be.

**Comment by rajnandini-tambavekar** [comment]
No problem & thanks for responsing
