### ISSUE TITLE
Add If Me - app to share mental health experiences with loved ones

### ISSUE THREAD

**Issue by shubheksha** [freeCodeCamp/how-to-contribute-to-open-source#5]
https://github.com/julianguyen/ifme
Issue label: [newbiefriendly](https://github.com/julianguyen/ifme/issues?q=is%3Aissue+is%3Aopen+label%3Anewbiefriendly)

**Comment by bismarkhenao** [comment]
I can work on this :)

**Comment by erictleung** [comment]
To those who haven't contributed before to this repository or are wanting to get more comfortable contributing, please take a look at #280 for an example of what is needed for this issue.

**Comment by inezabonte** [comment]
Hi, first time contributing. Can I work on this?
