### ISSUE TITLE
Add reasoning to translation in CONTRIBUTING

### ISSUE THREAD

**Issue by marsonya** [freeCodeCamp/how-to-contribute-to-open-source#500]
The README.md file is almost all links to very awesome resources for Open Source Contribution. But I don't get the point of translating the list of links. 
I mean, the resources the translated guide links to are still in English.

EDIT:-
The repo is full of very information useful. No disrespect to any of the contributors. 
I am just trying to understand the reason for translating the list of links while the resource being linked is still in English.

**Comment by erictleung** [comment]
Thanks for the question. This repository is about contributing to open source and generally, translation is important to reaching diverse audiences. So naturally, we should include translation as an important contribution to open source.

However, you have a valid point about most of the links being in English. I have seen a few (although not a lot) of contributions of language-specific links. So even though, yes, many of the links are going to English-written resources, there is the potential for language-specific links as well.

I hope that makes sense. And thanks for the constructive criticism.

**Comment by erictleung** [comment]
To make it clear, we can add an explanation and reasoning in our CONTRIBUTING document as to why we're translating the README even though most of the links are towards English written posts.

https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/CONTRIBUTING.md#adding-to-non-english-readme
