### ISSUE TITLE
Translate to malayalam

### ISSUE THREAD

**Issue by varghesejose2020** [freeCodeCamp/how-to-contribute-to-open-source#515]
Malayalam is my native language and I would like to contribute by translating it to Malayalam.

**Comment by erictleung** [comment]
Great! Feel free to translate the `README.md` file to Malayalam. Please also, if possible, have someone else who knows Malayalam to review your translation when you or someone else makes the pull request.

**Comment by Arun-kc** [comment]
I would like to help with this contribution. @varghesejose2020 @erictleung

**Comment by varghesejose2020** [comment]
:+1:  @Arun-kc

**Comment by varghesejose2020** [comment]
@Arun-kc      https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/526

**Comment by varghesejose2020** [comment]
help wanted

**Comment by erictleung** [comment]
Closed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/526
