### ISSUE TITLE
Add "Getting Started with Open Source" by NumFocus

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#525]
https://github.com/numfocus/getting-started-with-open-source

**Comment by iamayushdas** [comment]
Not getting the issue clearly. Can you brief more?

**Comment by erictleung** [comment]
Sorry for the brief. I found this repo that has a number of resources to get started with open source.

I think this article can be added to the [Contributing to Open Source in general](https://github.com/freeCodeCamp/how-to-contribute-to-open-source#contributing-to-open-source-in-general) section in our repository here.

If you want to contribute to it, feel free. I hope that gives this issue a little more context.

**Comment by vj-codes** [comment]
@erictleung hey I would like to work on this:)
