### ISSUE TITLE
Add GitHub's list of resources for git and GitHub

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#53]
Add under "Version control" section.

https://help.github.com/articles/git-and-github-learning-resources/

**Comment by andrewnding** [comment]
Hi, I'm a first time contributor. I'd like to take this on to practice contributing!

**Comment by erictleung** [comment]
@andrewnding go for it! So what I'm suggesting to do in this issue is to just take that link above and put it under the "Version control" section. Let us know in the [Contributors Gitter chat room](https://gitter.im/FreeCodeCamp/Contributors) if you have any questions contributing.

**Comment by satyadeeproat** [comment]
Hi @erictleung Just wanted to start contributing. So should i make a new branch after cloning or work in the master ?

**Comment by andrewnding** [comment]
I've already pushed a commit #55 that addresses this issue

**Comment by erictleung** [comment]
@andrewnding thanks for the pull request! I've been busy at a conference the past couple days so I haven't been able to look at your pull request. Also, for future reference, you can close issues from your pull request using [GitHub keywords](https://help.github.com/articles/closing-issues-via-commit-messages/). So for this issue, within your pull request made on GitHub, you can add `Closes #53` in the text area to refer to this issue so that others can see you've made a pull request. I'll take a look at your pull request right now.

@satyadeeproat apologies, but it appears @andrewnding has already made a pull request addressing this issue. There are a number of other similar issues in this repository's list of issues. So feel free to tackle any of those.

**Comment by erictleung** [comment]
Fixed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/55.

**Comment by andrewnding** [comment]
Thanks I didn't know about the commit message I'll do that in the future!
