### ISSUE TITLE
Making a Pull Request 

### ISSUE THREAD

**Issue by chryzcodez** [freeCodeCamp/how-to-contribute-to-open-source#544]
I tried making a #543 [pull request](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/543) in adding a [github repository](https://github.com/chryz-hub/opensource-4-everyone) on opensource to this repository but the [github actions](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/actions/runs/617494739) kept failing and I do not know what the issue was!

**Comment by noah-vdv** [comment]
That problem has been fixed in PR #538 but it just needs to get merged

**Comment by chryzcodez** [comment]
Okay, thanks.

I would be expecting the merge to be made in no time, So that mine can be reviewed also!

**Comment by erictleung** [comment]
Thanks for your all of your patience. Yes, as @noah-vdv noticed, there were some other links that were having some issues. I've merged https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/538, so this shouldn't be an issue. So closing as resolved. Happy coding!

**Comment by chryzcodez** [comment]
Yeah, thanks. My contribution has been merged.
