### ISSUE TITLE
Add a book in Open Source books section.

### ISSUE THREAD

**Issue by yasht01** [freeCodeCamp/how-to-contribute-to-open-source#545]
Hey!
I found a book [Open Advice](http://open-advice.org/) that could be really useful for beginners when they start contributing to free software.

**Comment by yasht01** [comment]
Can I add this in the README.md?

**Comment by erictleung** [comment]
@yasht01 thanks for finding and sharing this resource. We welcome this addition to this repository. This resource can be added to the section "Contributing to Open Source in general". Let me know if you  need any help contributing.

**Comment by yasht01** [comment]
Hey @erictleung 👋
Thanks for the reply. I will work on this and make a PR as soon as possible.

**Comment by yasht01** [comment]
Hey @erictleung 
I have made a PR, but the checks are failing. Can you point out what is wrong?

**Comment by erictleung** [comment]
@yasht01 thanks for the PR. I've merged it. Regarding the checks failing, that is because of another link that doesn't pass our checks. I wouldn't worry about it for now. Happy coding!
