### ISSUE TITLE
Problems making my first pull request

### ISSUE THREAD

**Issue by smijal** [freeCodeCamp/how-to-contribute-to-open-source#546]
I just finished translation #542, but the checks keep failing. The log shows multiple problems with the links 404 errors and page not found. Do I need to remove all the failing links or there is something else that I am doing wrong. Thank you.

**Comment by noah-vdv** [comment]
That problem has been fixed in PR #538 but it just needs to get merged

**Comment by erictleung** [comment]
@smijal thanks for your pull request! The pull request is failing because of links that don't have to deal with the changes you've made. These changes have been updated, so you don't have to worry about fixing them in this pull request you've made. Closing as not an issue anymore. Happy coding!
