### ISSUE TITLE
Adding the list of open source programs

### ISSUE THREAD

**Issue by manastole03** [freeCodeCamp/how-to-contribute-to-open-source#551]
## Introduction

Hey, I am Manas Tole. I am an engineering student and I am having an experience in open source contribution.
This repository is so useful for newbies as well as for experts to start their contribution in open source. The related articles are too good and written by  well experienced people. 
But I found a small issue in this repository which is mentioned below.
 
## Issue

New programmers don't know about some great opportunities and this will happens with some expert programmers too. we have some great open source contribution programs like :  
i) Google Summer of Code (GSOC)
ii) FSF. FSF – 
iii) X.Org Endless Vacation of Code. ...
iv) RGSOC. ...
v) SOCIS. ...
vi) DataONE.
but due to lack of knowledge or importance they missed their chance for a great open source contribution.

## Solution 
 So to over some the above mentioned issue we have to mention the list all the open source programs in this repository and some of their important points  such as 🔢 
1) Eligibility Criteria
2) Working Period
3) Application period 
4) Application process
5) Level of that programs

By adding this information to this repository will definitely help to add more value to this repository.

Please assign this task to me I will happy to work on this :) 
Thank you 

## Mentions

@kant @matteobruni @SaintPeter @hzoo @paulywill @saaketporay @Sagar2366 @sametcl2 @sachin161kr 
@AAA530 @abhi526691 @AemieJ @ahammadshawki8 @ahmadabdolsaheb @BaseMax @batuhantastekin @beaucarnes @betheymc @bfmcneill @cBridges851 @Chandra158 @cmccormack @CoderRx001 @coni2k @danthareja @davidpucheta @dev-oswld @DeveloperAspire @Dhaxor @elgaspar @EliasHjelm @EmilePW @ericboucher @erictleung @frantsen @gfunk81 @Ifyokoh @tfloyd95

**Comment by erictleung** [comment]
@manastole03 thanks for sharing. These are some great initiative for people wanting to contribute to open source.

These resources can be added to the section "Open Source contribution initiatives".

You don't have to worry about the other languages if you don't have time for or have expertise in that language.

**Comment by BaseMax** [comment]
We look forward to seeing this list. @manastole03

Best wishes for you

**Comment by manastole03** [comment]
Thank a lot @erictleung & @BaseMax
