### ISSUE TITLE
Add "Ten simple rules for helping newcomers become contributors to open projects"

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#558]
Add this article to contributing to open source in general section

https://doi.org/10.1371/journal.pcbi.1007296

**Comment by nishanttyagi18** [comment]
Hi, can i work on this?

**Comment by erictleung** [comment]
@nishanttyagi18 go for it! Let me know if you have any questions about contributing 👍

**Comment by nishanttyagi18** [comment]
Thanks, right now i don't have any.
