### ISSUE TITLE
Add Travis CI build badge to README

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#58]
To show the build status of the project, we should add a badge.

The README should look something like this:

```
# Welcome newbie open source contributors! 

[![Build Status](https://travis-ci.org/freeCodeCamp/how-to-contribute-to-open-source.svg?branch=master)](https://travis-ci.org/freeCodeCamp/how-to-contribute-to-open-source)

This is a list of resources for people who are new to contributing to open source.

...
```

Which will render to something like this:

# Welcome newbie open source contributors! 

[![Build Status](https://travis-ci.org/freeCodeCamp/how-to-contribute-to-open-source.svg?branch=master)](https://travis-ci.org/freeCodeCamp/how-to-contribute-to-open-source)

This is a list of resources for people who are new to contributing to open source.

**Comment by frantsen** [comment]
Can I take this?

**Comment by frantsen** [comment]
Can I take this too?
