### ISSUE TITLE
translate README.md to malayalam

### ISSUE THREAD

**Issue by ZedanSaheer** [freeCodeCamp/how-to-contribute-to-open-source#587]
Hello my native language is **Malayalam** , and i would like to _translate_ the _readme.md_ to **Malayalam**!

**Comment by mr-speedster** [comment]
https://github.com/deepushajia/ASCII-Unicode-Converter-for-Malayalam.git

use this may be works

**Comment by erictleung** [comment]
Closing in favor of https://github.com/freeCodeCamp/how-to-contribute-to-open-source/issues/515. Happy coding!
