### ISSUE TITLE
Add badges to label PR friendliness

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#59]
Add the following to the README

```
# Welcome newbie open source contributors!

[![Pull Requests Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat)](http://makeapullrequest.com) 
[![first-timers-only Friendly](https://img.shields.io/badge/first--timers--only-friendly-blue.svg)](http://www.firsttimersonly.com/)

This is a list of resources for people who are new to contributing to open source.
```

Which will render something like this:

# Welcome newbie open source contributors!

[![Pull Requests Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat)](http://makeapullrequest.com) [![first-timers-only Friendly](https://img.shields.io/badge/first--timers--only-friendly-blue.svg)](http://www.firsttimersonly.com/)

This is a list of resources for people who are new to contributing to open source.

**Comment by srajappa** [comment]
Raised a PR :) please review :)

**Comment by erictleung** [comment]
Closing as fixed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/62.
