### ISSUE TITLE
READ.ME translating to Farsi(Persian)

### ISSUE THREAD

**Issue by acse-srm3018** [freeCodeCamp/how-to-contribute-to-open-source#598]
Hello everyone, I would like to translate the readme.md to Farsi(Persian) to make it easier to understand for Persian natives speakers.

**Comment by najmieh** [comment]
@acse-srm3018 I can do this.

**Comment by erictleung** [comment]
Looks like we already have a Persian translation added here https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/322. Closing as done. But you're welcome to improve the translations with your own pull request. Happy coding!

**Comment by grze888siu** [comment]
- [ ]
