### ISSUE TITLE
Have awesome_bot check the PROJECTS.md file

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#60]
Change the [`package.json`](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/package.json) file to check the [`PROJECTS.md`](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/PROJECTS.md) file as well in validating links

```diff
    "scripts": {
-     "test": "awesome_bot --allow-redirect --allow-ssl README.md",
+     "test": "awesome_bot --allow-redirect --allow-ssl README.md PROJECTS.md",
    "pretest": "npm run lint",
```

**Comment by frantsen** [comment]
Can I take this too?
