### ISSUE TITLE
Fix missing parenthesis in the PROJECTS.md file

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#61]
See below. There is a missing parenthesis for the contributing guide, so the formatting is messed up.

## Screenshot

![image](https://user-images.githubusercontent.com/2754821/27064767-e3a672b8-4fad-11e7-9a6d-7b541f2ffe2c.png)

**Comment by aparnaadesai** [comment]
@erictleung Can I claim this one and fix it?

**Comment by aparnaadesai** [comment]
Created a pull request for this issue https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/63
