### ISSUE TITLE
Add a link to FOSS Acronym

### ISSUE THREAD

**Issue by aloisdg** [freeCodeCamp/how-to-contribute-to-open-source#620]
Hello,

I have created a list to collect all the common acronyms I faced in my open source journey. Would it be useful to add it to this project? Here it is: [Foss Acronyms](https://github.com/d-edge/foss-acronyms).

[![image](https://user-images.githubusercontent.com/3449303/140753242-b1aa9bd0-3bd0-444c-a76d-1b84b2439b27.png)](https://github.com/d-edge/foss-acronyms#acronyms)

Cheers,

**Comment by iamrahulrnair** [comment]
i can work on this?

**Comment by iamrahulrnair** [comment]
Thanks, i could work on this

**Comment by uday03meh** [comment]
@iamrahulrnair Are you still working on this one?

**Comment by angieloux** [comment]
Hey, I noticed this was still open so I added the link & created the PR just now. Lmk if any issues! 
-AJ
