### ISSUE TITLE
I want to join your Github Organization. 

### ISSUE THREAD

**Issue by SensationalShubham** [freeCodeCamp/how-to-contribute-to-open-source#631]
**I Just saw your Open Source video on YouTube and I also want to join your Github Organization.**

**Comment by erictleung** [comment]
Hi @SensationalShubham! Thanks for your interest in helping out and even wanting to join our GitHub Organization! We usually add people to our organization who have made consistent contributions to our organization already. For example, I helped triage and help manage some of the GitHub Issues over at the [main repository](https://github.com/freecodecamp/freecodecamp/issues). After a while, the current moderators noticed my consistent help and added me to the organization.

There are other ways to contribute and make your way in if you put in the time https://contribute.freecodecamp.org/#/. Please take a look at see if there are other ways for you to contribute. Thanks and good luck! Happy coding!
