### ISSUE TITLE
Create funding file

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#636]
Create a `funding.yml` file in `.github/`.

The file should be

```
github: freecodecamp
patreon: freecodecamp
custom: [www.freecodecamp.org/donate]
```

See the main repository for what this should look like https://github.com/freeCodeCamp/freeCodeCamp/tree/main/.github.

**Comment by GAbdulWahab** [comment]
@erictleung  ok, can you assign it for me?

**Comment by erictleung** [comment]
@GAbdulWahab go for it! I don't need to assign you. Your comment is enough to claim this issue. Let me know if you need any more help.

**Comment by GAbdulWahab** [comment]
@erictleung  thank you so much
