### ISSUE TITLE
Translating README.md to Slovenian

### ISSUE THREAD

**Issue by Rozman123Rok** [freeCodeCamp/how-to-contribute-to-open-source#649]
Hello,  guys.

I'm a native Slovenian speaker and I would like to start contributing to the open-source. So I can create README-SI.md file for this project.

**Comment by antonio-erick** [comment]
That would be very good. You should look into [this](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/f417311e20e9dcbbb7813830d2bbf23dab55b85d/CONTRIBUTING.md).
