### ISSUE TITLE
Add concurrency check in GitHub Actions to cancel in-progress workflows

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#656]
Add these lines to the GitHub Actions workflow

```
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
```

This will prevent GitHub Actions to fire for multiple commits run quickly after each other, e.g., from typos.

This change needs to be added to this file https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/main/.github/workflows/test.yml.

For example, this is what needs to be done

```diff
name: Check Resources

on: [push,pull_request]

+ concurrency:
+   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
+   cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest

  ...
```

Inspired from this tweet https://twitter.com/sebastienlorber/status/1495776331287646209.

**Comment by Simba-97** [comment]
Hey @erictleung can I work on this?

**Comment by Simba-97** [comment]
Hey @erictleung I have created a PR #657 for the task, Please review and request code changes if any.

**Comment by erictleung** [comment]
@Simba-97 thanks for your patience. Just reviewed your PR and will be merged momentarily. Thanks!
