### ISSUE TITLE
Translation into Bengali (Want to rewrite the full README as the previous one has taken directly from Google Translator and sounds robotic)

### ISSUE THREAD

**Issue by FahimFBA** [freeCodeCamp/how-to-contribute-to-open-source#666]
Hello,
I am interested to translate this project into Bengali. As I am already working as a volunteer in the freeCodeCamp Bengali team, I think I would be able to translate the project all by myself. I just noticed that it has already been translated to Bengali, but many of the lines are translated using the **Google Translate** which makes the translated version more robotic. I want to make changes to the `README-BN.md` file.

Please let me know what do you think about that.

**Update:** I have already started working on this issue.

**Comment by SiddheshKukade** [comment]
I think you should just go for it 👍

**Comment by erictleung** [comment]
@FahimFBA thanks for your observation. We depend on others to see there is improvements that can be made.

Here's a direct link to the associated README file: https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/main/README-BN.md

In your pull request, you can add this to the body of the pull request to automatically close this issue.

```
Closes #666
```

Feel free to create a branch of yours, make changes, and then submit a pull request. Let us know if you have any questions about how to do this.

**Comment by FahimFBA** [comment]
Thank you, @erictleung. I am doing everything according to your instruction. Please give me some days until I finish the task.

**Comment by erictleung** [comment]
@FahimFBA happy to help. And no rush, do it at the pace that works for you and your life. Thanks for your time 👍

**Comment by FahimFBA** [comment]
Please mention not. :) I am working on this issue!
