### ISSUE TITLE
Add "Try Git" to "Using version control" section

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#67]
Description: "Learn Git in your browser for free"

Link: https://try.github.io

**Comment by Logan1x** [comment]
I would like to work on this @erictleung

**Comment by erictleung** [comment]
@Logan1x unfortunately, someone's already made a pull request to fix this (https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/68). However, there's plenty of other issues in this repository to work on, so feel free to find another one to work on.

**Comment by Logan1x** [comment]
It's okay 😊

**Comment by erictleung** [comment]
Closed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/68

**Comment by Simfa11** [comment]
I would like to contribute...Please how do i contribute

**Comment by erictleung** [comment]
@Simfa11 thanks for your interest in contributing! Please take a look at the open issues and find one you'd like to work on https://github.com/freeCodeCamp/how-to-contribute-to-open-source/issues :+1:
