### ISSUE TITLE
Hey i would like to translate your readme file into Hindi 

### ISSUE THREAD

**Issue by Light-coder777** [freeCodeCamp/how-to-contribute-to-open-source#679]

**Comment by erictleung** [comment]
Hello @Light-coder777! Welcome. Thank you for your enthusiasm, but our repository has already been translated to Hindi https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/main/README-HI.md. If you want to take a look at it, feel free to make a pull request to improve the translation if you see any room for improvement. Happy coding!
