### ISSUE TITLE
Add Read The Docs

### ISSUE THREAD

**Issue by shubheksha** [freeCodeCamp/how-to-contribute-to-open-source#7]
http://docs.readthedocs.io/en/latest/index.html

[Contributing guide](http://docs.readthedocs.io/en/latest/contribute.html)
Issue label: [Good First Bug](https://github.com/rtfd/readthedocs.org/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Bug%22)

**Comment by shrawnz** [comment]
Could you help me out on this one? I'd like to work on it

**Comment by namratab94** [comment]
Hello,
Is anyone working on this issue?

**Comment by erictleung** [comment]
@namratab94 go for it! As with the other issue, feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

**Comment by namratab94** [comment]
@erictleung Thank you so much!

**Comment by erictleung** [comment]
Closed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/79.
