### ISSUE TITLE
Update GitHub Guides link

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#702]
Our CI flags this as a redirect and is suggesting to use the full URL instead.

```diff
- - [GitHub Guides](https://guides.github.com/) - basic guides on how to use GitHub effectively.
+ - [GitHub Guides](https://docs.github.com/) - basic guides on how to use GitHub effectively.
```

**Comment by Simba-97** [comment]
I would like to work on this, could you assign it to me

**Comment by erictleung** [comment]
Hi @Simba-97, thanks for your enthusiasm to help out! I see that you've contributed to our repo before. I've created this issue for first-time contributors to give them a chance to learn as well. So if you can, please keep this open for others to try as well. Thanks!

**Comment by marahim20** [comment]
@erictleung can I take this on?

**Comment by SangamSwadiK** [comment]
@erictleung Hi, updated the URL to the full URL.  
PR : #732
