### ISSUE TITLE
Update First Timers Only link

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#703]
Our CI flags this as a redirect and is suggesting to use the full URL instead. Here, we just need to remove that single forward slash at the end.

```diff
- - [First Timers Only](https://kentcdodds.com/blog/first-timers-only/) by [@kentcdodds](https://github.com/kentcdodds)
+ - [First Timers Only](https://kentcdodds.com/blog/first-timers-only) by [@kentcdodds](https://github.com/kentcdodds)
```

**Comment by erictleung** [comment]
@GAbdulwhb hello! It appears you've had some experience contributing to this repo already. I've labeled this issue for first-timers only, so I will leave this open for less experienced developers to practice contributing. I hope you understand. Thanks and happy coding!

**Comment by GAbdulwhb** [comment]
@erictleung 
Well sir, I'm sorry for that, I didn't know <3

**Comment by marahim20** [comment]
@erictleung can I take this on?

**Comment by erictleung** [comment]
@marahim20 hi there! Yes, you may take this issue on. Note, I did see your other comment in another issue here https://github.com/freeCodeCamp/how-to-contribute-to-open-source/issues/702#issuecomment-1151775111. If you work on this issue #703, then please leave #702 for another person as you will no longer be a first time contributor to our repository. I hope that makes sense. Let us know if you have any questions about contributing! Good luck!

**Comment by marahim20** [comment]
Sure! I'm going with this one
