### ISSUE TITLE
Update First Mission: Contributors Page link

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#705]
Our CI flags this as a redirect and is suggesting to use the full URL instead.

```diff
- - [First mission: Contributors page](https://medium.com/@forCrowd/first-mission-contributors-page-df24e6e70705#.2v2g0no29) by [@forCrowd](https://github.com/forCrowd)
+ - [First mission: Contributors page](https://forcrowd.medium.com/first-mission-contributors-page-df24e6e70705) by [@forCrowd](https://github.com/forCrowd)
```

**Comment by Simba-97** [comment]
I would like to work on this

**Comment by erictleung** [comment]
Hi @Simba-97, thanks for your enthusiasm to help out! I see that you've contributed to our repo before. I've created this issue for first-time contributors to give them a chance to learn as well. So if you can, please keep this open for others to try as well. Thanks!
