### ISSUE TITLE
Update What open-source should I contribute to link

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#706]
Our CI flags this as a redirect and is suggesting to use the full URL instead.

```diff
- - [What open-source should I contribute to](https://kentcdodds.com/blog/what-open-source-project-should-i-contribute-to/) by [@kentcdodds](https://github.com/kentcdodds)
+ - [What open-source should I contribute to](https://kentcdodds.com/blog/what-open-source-project-should-i-contribute-to) by [@kentcdodds](https://github.com/kentcdodds)
```

**Comment by uday03meh** [comment]
Hi @erictleung! I have made a PR for this issue, but it shows failed checks. Can you please help me resolve this?

https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/715

**Comment by erictleung** [comment]
@uday03meh as I mentioned in those PRs, I'm leaving this issue to first time contributors. You are right that this fails the automated tests, but I'll let others practice with this change. Thanks!

**Comment by prasanta10** [comment]
@erictleung I would like to contribute.

**Comment by erictleung** [comment]
@prasanta10 go for it! Let us know if you have any questions or issues contributing. Good luck!
