### ISSUE TITLE
Remove unnecessary spaces in listing

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#73]
## Issue

In the README and under the listing for the Do's and Don'ts, there are unnecessary spaces in the description.

![image](https://user-images.githubusercontent.com/2754821/29508527-bc425876-8609-11e7-84b7-40aaf471fe62.png)

## To Contribute

Check out our [CONTRIBUTING.md](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/CONTRIBUTING.md) document for details and help for contributing.

When making the pull request to make these changes, be sure to include `Closes #73` in the pull request body so it references this issue. Good luck!

**Comment by tracypholmes** [comment]
If it's my first time helping out on your codebase/documentation, is that acceptable? If so, I would like to grab this one.

**Comment by rsarky** [comment]
I have submitted a pull request for this issue.Could you please review it. @erictleung 
#74

**Comment by erictleung** [comment]
@tracypholmes hi there! Sorry I got to this too late. Unfortunately, it appears someone has already picked this up and submitted a pull request. Luckily, there are many other issues that are of a similar contributing level. Free feel to take a look at the other issues and let me know if you have any questions on helping out :+1: 

@rsarky I'll still consider your pull request, but next time, please be courteous to others and check the issue you're going to make a pull request in case others have asked about contributing.

**Comment by tracypholmes** [comment]
No problem @erictleung and thank you! Will def check things out!

**Comment by erictleung** [comment]
Closing as the issue is resolved by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/74. Happy coding!

**Comment by rsarky** [comment]
I am extremely sorry @tracypholmes.
Next time I will surely ask before working on a issue.@erictleung
Thanks a lot for the help.
