### ISSUE TITLE
Request to admit me in the organization.

### ISSUE THREAD

**Issue by manandraj20** [freeCodeCamp/how-to-contribute-to-open-source#738]

**Comment by erictleung** [comment]
@manandraj20 thanks for your interest in joining our organization! Membership into our organization is based on consistent involvement in our community over time. Feel free to take a look here for ways to help out https://contribute.freecodecamp.org/. Also feel free to read over this FAQ about being a moderator https://contribute.freecodecamp.org/#/FAQ?id=i-am-interested-in-being-a-moderator-at-freecodecamp-where-should-i-start. Good luck and happy coding!
