### ISSUE TITLE
Replace build status badge in README

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#746]
We are no longer relying on Travis CI to test this repository, rather we are using GitHub Actions. So we can replace the build status.

```diff
- [![Build Status](https://api.travis-ci.org/freeCodeCamp/how-to-contribute-to-open-source.svg?branch=master)](https://travis-ci.org/freeCodeCamp/how-to-contribute-to-open-source)
+ [![Check Resources](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/actions/workflows/test.yml/badge.svg)](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/actions/workflows/test.yml)
```

At the very least, this should be done for the [main README.md file](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/main/README.md), but ideally, this should be replaced in all the README language variations as well.

**Comment by Safirangi** [comment]
Hey, can I work on this issue?

**Comment by melvincwng** [comment]
@erictleung, just to provide some context here:

In PR #747, @kum9748ar has already replaced the build status badge for the main README.md
In my PR #748, I have replaced the build status badges for all the remaining README language variations.

There is no merge conflict, but please kindly review & approve the changes.

Thanks!
