### ISSUE TITLE
Replace GitHub Learning Lab with GitHub Skills

### ISSUE THREAD

**Issue by OrneryCash** [freeCodeCamp/how-to-contribute-to-open-source#751]
## Suggested link

https://skills.github.com

## Reasoning
 
Due to GitHub Learning Lab will shut down on September 1, 2022. So It will be more useful if we replace with GitHub Skills

## Section

- ["GitHub Learning Lab"](https://lab.github.com/) - Level up your skills with GitHub Learning Lab. Our friendly bot will take you through a series of fun, practical projects to learn the skills you need in no time—and share helpful feedback along the way.

**Comment by Oberkoh** [comment]
I intend to work on fixing this issue

**Comment by OrneryCash** [comment]
@Oberkoh, Thank you for your contribution. But please make the pull request to freeCodeCamp repository.

**Comment by OrneryCash** [comment]
Done. Wait for this pull request to be merged. And then I close this issue. Thank you so much for your contribution. Have a nice day.
