### ISSUE TITLE
Target all README files in GitHub Actions check

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#755]
This will most likely cause issues with the CI tests to pass, but I think it is time we target and check all README files in our repository.

```diff
        run: |
          gem install awesome_bot
          awesome_bot \
-            -f README.md \
+            -f README.md,README-*.md \
            --allow-ssl \
            --allow 302,429 \
            --white-list firsttimersonly.com,github.com/github,creativecommons.org/licenses/by-sa/4.0,github.com/kentcdodds
```

File: https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/main/.github/workflows/test.yml

**Comment by madhhuurrii** [comment]
Hi @erictleung , I would like to contribute!

**Comment by JeetDSharma** [comment]
Hey @erictleung, I am interested to make changes and contribute for the first time!

**Comment by erictleung** [comment]
@JeetDSharma thanks for your enthusiasm to contribute! It appears that @madhhuurrii has already claimed and made a pull request for this change. Please take a look at other issues and see if you can contribute. Otherwise, take a look at our README for other places to contribute. Thanks!
