### ISSUE TITLE
Incorrect article name needs fixing

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#78]
Within the section [Useful articles for new open source contributors](https://github.com/freeCodeCamp/how-to-contribute-to-open-source#useful-articles-for-new-open-source-contributors), there is a typo in the article [How to Find a Bug in Your Code](https://8thlight.com/blog/doug-bradbury/2016/06/29/how-to-find-bug-in-your-code.html).

```diff
- - ["How to find a bug in code"](https://8thlight.com/blog/doug-bradbury/2016/06/29/how-to-find-bug-in-your-code.html) by [@dougbradbury](https://twitter.com/dougbradbury)
+ - ["How to Find a Bug in Your Code"](https://8thlight.com/blog/doug-bradbury/2016/06/29/how-to-find-bug-in-your-code.html) by [@dougbradbury](https://twitter.com/dougbradbury)
```

**Comment by namratab94** [comment]
Hello,
Is anyone working on this? If not, then can I?

**Comment by erictleung** [comment]
@namratab94 go for it! Feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/Contributors) chat room if you have any questions about helping. We're there to help.

**Comment by shovanch** [comment]
Would love to work this. This would be my first open source contribution

**Comment by erictleung** [comment]
@shovanch it looks like @namratab94 has already said they are working on it. It's only been several days since. I'll give them a total of a week to make the changes unless @namratab94 wants to comment on their status.

You can always take a look at the other issues in this repository for other issues to tackle. Thanks for your interest in contributing!

**Comment by shovanch** [comment]
@erictleung Thanks for the response. I'll keep a look out

**Comment by namratab94** [comment]
@erictleung @shovanch I was figuring out how to make a contribution to the repo and was working on issue #7. I have not abandoned this issue yet and will start working on this by tonight.

**Comment by erictleung** [comment]
Fixed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/83. Closing as resolved. Happy coding!
