### ISSUE TITLE
Translate README.md to Urdu

### ISSUE THREAD

**Issue by Muhammad-Shahid-Jamal** [freeCodeCamp/how-to-contribute-to-open-source#780]
My native language is Urdu and I saw there is no full version available for that file in the Urdu language.

**Comment by Muhammad-Shahid-Jamal** [comment]
Hi, @erictleung  kindly assign this issue to me so I can contribute to this.

**Comment by aakarshan-raj** [comment]
I think you can contribute without being assigned to it.

**Comment by m-shahzaib-anwar** [comment]
you can contribute without being assigned. Just create PR

**Comment by erictleung** [comment]
Closing as duplicate of https://github.com/freeCodeCamp/how-to-contribute-to-open-source/issues/485.
