### ISSUE TITLE
GitHub Workflow checks fail due to bad links in README.md

### ISSUE THREAD

**Issue by VahilaK** [freeCodeCamp/how-to-contribute-to-open-source#783]
**Looking forward for reporting a security issue:**
Please report security issues by following our security policy: `https://contribute.freecodecamp.org/#/security`

**Describe the bug**
Few links in README.md have 301 and 502 status based on [this](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/runs/7930232978?check_suite_focus=true#step:4:157) action log. Because of these links, the workflow is failing.

**To Reproduce**
1. Run the 'test.yml' workflow file from GitHub Actions

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by VahilaK** [comment]
@erictleung I can take this up. I am planning to update the links with 301 status code to new redirected links and remove the content related to the 502 status link. Let me know your views.

**Comment by erictleung** [comment]
@VahilaK thanks for making this issue. I'm aware of this issue. Feel free to fix some links in the README files, but no pressure to fix all the file links because there are a lot. Also, we can keep this issue open for others to refer to this and fix as well.

**Comment by VahilaK** [comment]
@erictleung I have fixed some links in README-AR file but there are some duplicate links which are still shown as flags for this file. Most of these links are in '--white-list' but there are new duplicate links added. 

I looked into the documentation of 'awesome_bot' and we can leverage '--allow-dupe' to avoid duplicates or we can remove the duplicate links. Let me your thoughts.

**Comment by Arijit1000** [comment]
@erictleung @VahilaK I see some of the workflows of the Readme file are failing in the Github actions and it is returning "Process completed with exit code 1." Can you have a look into this issue?

**Comment by erictleung** [comment]
Closing as fixed and CI checks no longer failing. Happy coding!
