### ISSUE TITLE
issue with hindi translation

### ISSUE THREAD

**Issue by aakarshan-raj** [freeCodeCamp/how-to-contribute-to-open-source#788]
Translation to hindi of readme file is incomplete and have inconsistency with translation, i will try to fix it as soon as i can.

**Comment by harish343** [comment]
can I work on this issue

**Comment by uuc110** [comment]
@aakarshan-raj is it still open? and what's the issue maybe I can help with this

**Comment by aakarshan-raj** [comment]
issue was fixed way earlier, sorry for keeping this open

**Comment by rajneesh-18** [comment]
> issue was fixed way earlier, sorry for keeping this open

No worries
