### ISSUE TITLE
Add SymPy

### ISSUE THREAD

**Issue by shubheksha** [freeCodeCamp/how-to-contribute-to-open-source#8]
http://sympy.org/

[Dev Wiki](https://github.com/sympy/sympy/wiki#development)
[Work Flow](https://github.com/sympy/sympy/wiki/Development-workflow)
[Introduction to contributing](https://github.com/sympy/sympy/wiki/Introduction-to-contributing)
Issue label: [Easy To Fix](https://github.com/sympy/sympy/issues?q=is%3Aissue+is%3Aopen+label%3A%22Easy+to+Fix%22)

**Comment by HimadriNitk** [comment]
I would like to work on this issue. Could you help me out?

**Comment by bismarkhenao** [comment]
@erictleung should be closed this issue?

**Comment by erictleung** [comment]
@bismarkhenao yes, thanks for the heads up.
