### ISSUE TITLE
Complete Guide to Open Source - How to Contribute

### ISSUE THREAD

**Issue by pranjal779** [freeCodeCamp/how-to-contribute-to-open-source#800]
## Suggested link

[Complete Guide to Open Source - How to Contribute](https://www.youtube.com/watchv=yzeVMecydCE&ab_channel=freeCodeCamp.org) by Eddie Jaoude FreeCodeCamp, Youtube video.

## Reasoning

I got the basics of contributing to open source project, from your, FreeCodeCamp's Youtube Channel video Complete Guide to Open Source - How to Contribute,
since this link was not mentioned here I thought I need this to be added here. and so everyone can have access to this link.

## Section
 
Contributing to Open Source in general

**Comment by pranjal779** [comment]
> 
what should I do now?
is there any specific way to add the link or I do not have the previliage to add link?
I dont understand 
please advice

**Comment by Arijit1000** [comment]
> > 
> 
> what should I do now? is there any specific way to add the link or I do not have the previliage to add link? I dont understand please advice

Please check the link once. It is not redirecting to the original page. You can attach the link once again over here, after checking.
