### ISSUE TITLE
Readme file in Punjabi language

### ISSUE THREAD

**Issue by sachinkhatripro** [freeCodeCamp/how-to-contribute-to-open-source#808]
Hi,
I see there's no Punjabi language translation Readme file . May I please be assigned the job to translate and submit the same?

**Comment by mandeepsng** [comment]
@sachinkhatripro,  I will help you for Punjabi translation

**Comment by ArbazShaikh077** [comment]
**Is the issue still open?**

**Comment by sachinkhatripro** [comment]
Repo has gone cold. No use attempting it.

**Comment by rohanvaish95** [comment]
can i attempt my first time
