### ISSUE TITLE
Translate README.md to Gujarati

### ISSUE THREAD

**Issue by Bhavya031** [freeCodeCamp/how-to-contribute-to-open-source#822]
## Suggested link
https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/main/README.md

## Reasoning
Gujarati is my native language and it will be very helpful to people who only speak and read in Gujarati.

**Comment by Bhavya031** [comment]
Translate README.md to Gujarati

**Comment by erictleung** [comment]
Closed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/826
