### ISSUE TITLE
Add any initiatives in this article not on our list

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#845]
## Suggested link

https://www.geeksforgeeks.org/best-open-source-programs-for-students-to-participate/

## Reasoning
 
We want to have a space for students and learners to practice their skills in open source. This link above shouldn't directly be added to our list. The point of the link is to take the links in this page and figure out which ones are not already in our README list. Those missing or not included in our list should be added accordingly.

## Section

https://github.com/freeCodeCamp/how-to-contribute-to-open-source#open-source-programs-to-participate-in

**Comment by c00kie123** [comment]
Hello, I am interested in doing this. Please assign it to me.

**Comment by c00kie123** [comment]
Hey, I added in as required but there seem to be an error while during checking. Can you help me take a look at it?Thanks!
