### ISSUE TITLE
Add CONTRIBUTING.md website

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#852]
## Suggested link

`https://contributing.md/`

![image](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/assets/2754821/64e5748e-c5db-4b98-a455-5eb2874ce1b5)

## Reasoning
 
Has general guidelines on contributions to open source

## Section

Contributing to open source in general

**Comment by mkbhru** [comment]
## please close this pull request as contributing.md is already there

**Comment by erictleung** [comment]
Apologies for the ambiguous issue body. This is an actual website, not just the CONTRIBUTE.md file itself. I've changed the message body to be more clear.
