### ISSUE TITLE
Naming of Readme

### ISSUE THREAD

**Issue by djv03** [freeCodeCamp/how-to-contribute-to-open-source#854]
all the readme has added "README.md in Gujarati" as title to it. although the readme are as same as language mentioned. It can create confusion for a person who is just checking out repo casually

**Comment by ruben-duarte** [comment]
Yes it can be confusing, it should say "README.md in -targerLanguage-"   but its in the commit description. I'm gonna try with Spanish and Portuguese

**Comment by erictleung** [comment]
Note, although the PR #895 closes this PR, the actual issue of this PR is simply just how GitHub shows the commits on the main page. It may seem confusing, but that commit/PR just happens to change all of those links. Happy coding!
