### ISSUE TITLE
Finding Good First Issues 

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#860]
## Suggested link

https://community.codenewbie.org/bdougie/finding-good-first-issues-33a6

## Reasoning
 
Recent, and published on Code Newbie, a trusted brand in the programming space.

## Section

Contributing to Open Source in general

**Comment by mnik7044** [comment]
Hii I am a beginner and want to get started with open source, what is it that I need to fix in this issue can you please make it clear @erictleung

**Comment by SaswataH** [comment]
Hey mnik7044
https://youtu.be/CML6vfKjQss

This is a short Youtube video that will give you a short understanding of what Open Source or how the whole scene works

**Comment by erictleung** [comment]
@mnik7044 welcome! This "issue" is nothing to fix, but to add the link that I've shared above into the corresponding README section. I hope that makes sense. Happy to clarify if you have more questions.

**Comment by Santhoshmani1** [comment]
Hello @erictleung . 
I want to work on this issue. 
I have a small question about where should I add the link in the readme.md file
Can I add the link in the useful articles for the new open source contributors section ? 
I will be happy to contribute to this project if you could clarify the question.
Thank you

**Comment by erictleung** [comment]
@Santhoshmani1 thanks for your interest. Yes, you can add the link to the useful articles for beginners section. Thanks!

**Comment by Santhoshmani1** [comment]
@erictleung  I have added the article under the section. please check & approve the pr.
Thank you
