### ISSUE TITLE
Other resources than blogs/github links

### ISSUE THREAD

**Issue by biscuitdelicious** [freeCodeCamp/how-to-contribute-to-open-source#875]
Hi there,

can we also share other resources than github/blogs? e.g. youtube links or forums

Blogs are nice to read but seeing a video and seeing live how he does the contribution I think it's more satisfactory.

Peace!

**Comment by ChadLaBombarde** [comment]
I don't see why not .. this is a vast environment.  I mean if it's not illegal... but I'm not the boss.
Peace
