### ISSUE TITLE
Italian translation in README-IT.md has some improvable idiomatic expressions

### ISSUE THREAD

**Issue by moDal7** [freeCodeCamp/how-to-contribute-to-open-source#940]
### Checklist
- [x] Search Through Issues
- [x] Find issue you want to work on
- [x] Check if someone else has already worked on and made a pull request on said issue
- [x] (Optional) Double check pull requests for someone who has worked on the pull request

The italian translation of the README file has some weird and anti-idiomatic expressions which could be improved to sound more natural and less directly translated from english. 
Some examples could be:
> Ogni Giorno Git
> Regole del volo Git

I am actively making this minor fixes.

**Comment by erictleung** [comment]
Closing as fixed. Happy coding!
