### ISSUE TITLE
Update language-check.yml file

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#989]
**Issue**

Currently, the validation script to check the language abbreviation for the README files is not passing correctly. This is due to the letters in this repo are capitalized, but the sourced table on Wikipedia are lowercase.

**Solution**

Add in a line to uppercase the two-letter language values.

Edit this file: https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/main/.github/workflows/language-check.yml

```diff
      run: |
        # Scrape ISO 639 language codes from the Wiki page
        wget -qO- https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes | \
        nokogiri -e 'puts $_.css(".wikitable td:nth-child(2)").map(&:text)' | \
-       sed -nr '/^.{0,2}$/p' > iso639.txt  # Grab only two letter values
+ 		sed -nr '/^.{0,2}$/p' | \  # Grab only two letter values
+       tr '[:lower:]' '[:upper:]' > iso639.txt  # Convert letter values to uppercase
```

**Comment by ruhi47** [comment]
Hey @erictleung , If you need help. I can help.
Assign me the issue and we can work it out together.
Thanks!

**Comment by erictleung** [comment]
@ruhi47 thanks for your interest! Feel free to make a PR and I can review it. Good luck!
